alter table DYEXTN_ENTITY_GROUP add (IS_CACORE_GENERATED number(1,0) default 0);

UPDATE 
(select DYEXTN_ENTITY_GROUP.LONG_NAME,DYEXTN_ENTITY_GROUP.SHORT_NAME,DYEXTN_ABSTRACT_METADATA.name from
DYEXTN_ENTITY_GROUP join DYEXTN_ABSTRACT_METADATA
on DYEXTN_ENTITY_GROUP.IDENTIFIER=DYEXTN_ABSTRACT_METADATA.IDENTIFIER AND (DYEXTN_ENTITY_GROUP.LONG_NAME IS NULL 
or DYEXTN_ENTITY_GROUP.SHORT_NAME IS NULL))temp
SET temp.LONG_NAME=temp.NAME,temp.SHORT_NAME=temp.NAME ;

alter table DYEXTN_FILE modify FILE_RECORD longblob;
commit;