alter table DYEXTN_ENTITY_GROUP add (IS_CACORE_GENERATED bit default 0);

UPDATE DYEXTN_ENTITY_GROUP,DYEXTN_ABSTRACT_METADATA
SET DYEXTN_ENTITY_GROUP.LONG_NAME=DYEXTN_ABSTRACT_METADATA.NAME,DYEXTN_ENTITY_GROUP.SHORT_NAME=DYEXTN_ABSTRACT_METADATA.NAME 
WHERE DYEXTN_ENTITY_GROUP.IDENTIFIER=DYEXTN_ABSTRACT_METADATA.IDENTIFIER AND (DYEXTN_ENTITY_GROUP.LONG_NAME IS NULL OR DYEXTN_ENTITY_GROUP.SHORT_NAME IS NULL);

alter table DYEXTN_FILE modify FILE_RECORD longblob;
commit;