create table DYEXTN_CALCULATED_ATTRIBUTE (IDENTIFIER bigint not null auto_increment, SOURCE_CAT_ATTR_ID bigint, TARGET_CAL_ATTR_ID bigint, CAL_CATEGORY_ATTR_ID bigint, primary key (IDENTIFIER));
alter table DYEXTN_CALCULATED_ATTRIBUTE add constraint FKEF3B77585697A453 foreign key (CAL_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);


