//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.02.17 at 12:38:09 PM GMT+05:30
//


package edu.common.dynamicextensions.util.xml.formdefinition;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subform element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="Subform">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice>
 *           &lt;element ref="{}Instances"/>
 *           &lt;element ref="{}SingleLineDisplay"/>
 *         &lt;/choice>
 *         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *         &lt;attribute name="showPaste" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instances",
    "singleLineDisplay"
})
@XmlRootElement(name = "Subform")
public class Subform {

    @XmlElement(name = "Instances")
    protected Instances instances;
    @XmlElement(name = "SingleLineDisplay")
    protected SingleLineDisplay singleLineDisplay;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected Boolean show;
    @XmlAttribute
    protected Boolean showPaste;

    /**
     * Gets the value of the instances property.
     *
     * @return
     *     possible object is
     *     {@link Instances }
     *
     */
    public Instances getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     *
     * @param value
     *     allowed object is
     *     {@link Instances }
     *
     */
    public void setInstances(Instances value) {
        this.instances = value;
    }

    /**
     * Gets the value of the singleLineDisplay property.
     *
     * @return
     *     possible object is
     *     {@link SingleLineDisplay }
     *
     */
    public SingleLineDisplay getSingleLineDisplay() {
        return singleLineDisplay;
    }

    /**
     * Sets the value of the singleLineDisplay property.
     *
     * @param value
     *     allowed object is
     *     {@link SingleLineDisplay }
     *
     */
    public void setSingleLineDisplay(SingleLineDisplay value) {
        this.singleLineDisplay = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the show property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShow(Boolean value) {
        this.show = value;
    }

    /**
     * Gets the value of the showPaste property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isShowPaste() {
        return showPaste;
    }

    /**
     * Sets the value of the showPaste property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setShowPaste(Boolean value) {
        this.showPaste = value;
    }

}
