
drop table INTER_MODEL_ASSOCIATION;
drop table INTRA_MODEL_ASSOCIATION;
drop table ASSOCIATION;

create table ASSOCIATION(
    ASSOCIATION_ID    bigint    generated by default as identity,
    ASSOCIATION_TYPE  Decimal(31,0)    not null ,
    primary key (ASSOCIATION_ID)
);

create table INTER_MODEL_ASSOCIATION(
    ASSOCIATION_ID      bigint  not null references ASSOCIATION(ASSOCIATION_ID),
    LEFT_ENTITY_ID      bigint  not null,
    LEFT_ATTRIBUTE_ID   bigint  not null,
    RIGHT_ENTITY_ID     bigint  not null,
    RIGHT_ATTRIBUTE_ID  bigint  not null,
    primary key (ASSOCIATION_ID) 
);

create table INTRA_MODEL_ASSOCIATION(
    ASSOCIATION_ID    bigint    not null references ASSOCIATION(ASSOCIATION_ID),
    DE_ASSOCIATION_ID bigint    not null,
    primary key (ASSOCIATION_ID) 
);

drop table ID_TABLE;

create table ID_TABLE(
    NEXT_ASSOCIATION_ID    bigint    generated by default as identity,
    primary key (NEXT_ASSOCIATION_ID)
);

insert into ID_TABLE(NEXT_ASSOCIATION_ID) values(1);

commit;