DROP PROCEDURE @@SCHEMA_NAME@@.p1()#
CREATE PROCEDURE @@SCHEMA_NAME@@.p1()
BEGIN
 DECLARE maxid INTEGER;
 DECLARE stmttxt VARCHAR(100);

 	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_DATABASE_PROPERTIES ;
    SET stmttxt = 'ALTER TABLE DYEXTN_DATABASE_PROPERTIES ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from dyextn_permissible_value ;
    SET stmttxt = 'ALTER TABLE dyextn_permissible_value ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_ATTRIBUTE_TYPE_INFO ;
    SET stmttxt = 'ALTER TABLE DYEXTN_ATTRIBUTE_TYPE_INFO ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_ABSTRACT_METADATA ;
    SET stmttxt ='ALTER TABLE DYEXTN_ABSTRACT_METADATA ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_SEMANTIC_PROPERTY ;
    SET stmttxt = 'ALTER TABLE DYEXTN_SEMANTIC_PROPERTY ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_ROLE ;
    SET stmttxt = 'ALTER TABLE DYEXTN_ROLE ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_DATA_ELEMENT ;
    SET stmttxt = 'ALTER TABLE DYEXTN_DATA_ELEMENT ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_TAGGED_VALUE;
 	SET stmttxt = 'ALTER TABLE DYEXTN_TAGGED_VALUE ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
 	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_CONTAINER ;
    SET stmttxt = 'ALTER TABLE DYEXTN_CONTAINER ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_CONSTRAINTKEY_PROP ;
    SET stmttxt = 'ALTER TABLE DYEXTN_CONSTRAINTKEY_PROP ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_CONTROL ;
    SET stmttxt = 'ALTER TABLE DYEXTN_CONTROL ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

	select coalesce(max(IDENTIFIER)+1,1) into maxid from DYEXTN_RULE ;
    SET stmttxt = 'ALTER TABLE DYEXTN_RULE ALTER COLUMN IDENTIFIER RESTART WITH ' || CHAR(maxid);
	EXECUTE IMMEDIATE stmttxt;

END#
SET PATH = CURRENT PATH,@@SCHEMA_NAME@@#
call @@SCHEMA_NAME@@.p1()#
commit#