drop table ABSTRACT_CATEGORIAL_CLASS cascade constraints;
drop table ABSTRACT_CATEGORY cascade constraints;
drop table CATEGORIAL_ATTRIBUTE cascade constraints;
drop table CATEGORIAL_CLASS cascade constraints;
drop table CATEGORY cascade constraints;
drop table CURATED_PATH cascade constraints;
drop table CURATED_PATH_TO_PATH cascade constraints;
drop table DE_COLL_ATTR_RECORD_VALUES cascade constraints;
drop table DE_FILE_ATTR_RECORD_VALUES cascade constraints;
drop table DE_OBJECT_ATTR_RECORD_VALUES cascade constraints;
drop table DYEXTN_ABSTRACT_ENTITY cascade constraints;
drop table DYEXTN_ABSTRACT_FORM_CONTEXT cascade constraints;
drop table DYEXTN_ABSTRACT_METADATA cascade constraints;
drop table DYEXTN_ABSTRACT_RECORD_ENTRY cascade constraints;
drop table DYEXTN_ABSTR_CAT_ATTR cascade constraints;
drop table DYEXTN_ABSTR_CONTAIN_CTR cascade constraints;
drop table DYEXTN_ASSOCIATION cascade constraints;
drop table DYEXTN_ASSO_DISPLAY_ATTR cascade constraints;
drop table DYEXTN_ATTRIBUTE cascade constraints;
drop table DYEXTN_ATTRIBUTE_RECORD cascade constraints;
drop table DYEXTN_ATTRIBUTE_TYPE_INFO cascade constraints;
drop table DYEXTN_BARR_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_BASE_ABSTRACT_ATTRIBUTE cascade constraints;
drop table DYEXTN_BOOLEAN_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_BOOLEAN_TYPE_INFO cascade constraints;
drop table DYEXTN_BYTE_ARRAY_TYPE_INFO cascade constraints;
drop table DYEXTN_CADSRDE cascade constraints;
drop table DYEXTN_CADSR_VALUE_DOMAIN_INFO cascade constraints;
drop table DYEXTN_CALCULATED_ATTRIBUTE cascade constraints;
drop table DYEXTN_CATEGORY cascade constraints;
drop table DYEXTN_CATEGORY_ASSOCIATION cascade constraints;
drop table DYEXTN_CATEGORY_ATTRIBUTE cascade constraints;
drop table DYEXTN_CATEGORY_ENTITY cascade constraints;
drop table DYEXTN_CAT_ASSO_CTL cascade constraints;
drop table DYEXTN_CHECK_BOX cascade constraints;
drop table DYEXTN_COLUMN_PROPERTIES cascade constraints;
drop table DYEXTN_COMBOBOX cascade constraints;
drop table DYEXTN_CONSTRAINTKEY_PROP cascade constraints;
drop table DYEXTN_CONSTRAINT_PROPERTIES cascade constraints;
drop table DYEXTN_CONTAINER cascade constraints;
drop table DYEXTN_CONTAINMENT_CONTROL cascade constraints;
drop table DYEXTN_CONTROL cascade constraints;
drop table DYEXTN_DATABASE_PROPERTIES cascade constraints;
drop table DYEXTN_DATA_ELEMENT cascade constraints;
drop table DYEXTN_DATA_GRID cascade constraints;
drop table DYEXTN_DATEPICKER cascade constraints;
drop table DYEXTN_DATE_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_DATE_TYPE_INFO cascade constraints;
drop table DYEXTN_DOUBLE_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_DOUBLE_TYPE_INFO cascade constraints;
drop table DYEXTN_ENTITY cascade constraints;
drop table DYEXTN_ENTITY_GROUP cascade constraints;
drop table DYEXTN_ENTIY_COMPOSITE_KEY_REL cascade constraints;
drop table DYEXTN_FILE_EXTENSIONS cascade constraints;
drop table DYEXTN_FILE_TYPE_INFO cascade constraints;
drop table DYEXTN_FILE_UPLOAD cascade constraints;
drop table DYEXTN_FLOAT_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_FLOAT_TYPE_INFO cascade constraints;
drop table DYEXTN_FORMULA cascade constraints;
drop table DYEXTN_FORM_CTRL_NOTES cascade constraints;
drop table DYEXTN_INTEGER_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_INTEGER_TYPE_INFO cascade constraints;
drop table DYEXTN_LABEL cascade constraints;
drop table DYEXTN_LIST_BOX cascade constraints;
drop table DYEXTN_LONG_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_LONG_TYPE_INFO cascade constraints;
drop table DYEXTN_MULTISELECT_CHECK_BOX cascade constraints;
drop table DYEXTN_NUMERIC_TYPE_INFO cascade constraints;
drop table DYEXTN_OBJECT_TYPE_INFO cascade constraints;
drop table DYEXTN_PATH cascade constraints;
drop table DYEXTN_PATH_ASSO_REL cascade constraints;
drop table DYEXTN_PERMISSIBLE_VALUE cascade constraints;
drop table DYEXTN_PRIMITIVE_ATTRIBUTE cascade constraints;
drop table DYEXTN_RADIOBUTTON cascade constraints;
drop table DYEXTN_ROLE cascade constraints;
drop table DYEXTN_RULE cascade constraints;
drop table DYEXTN_RULE_PARAMETER cascade constraints;
drop table DYEXTN_SELECT_CONTROL cascade constraints;
drop table DYEXTN_SEMANTIC_PROPERTY cascade constraints;
drop table DYEXTN_SHORT_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_SHORT_TYPE_INFO cascade constraints;
drop table DYEXTN_SKIP_LOGIC_ATTRIBUTE cascade constraints;
drop table DYEXTN_SQL_AUDIT cascade constraints;
drop table DYEXTN_STRING_CONCEPT_VALUE cascade constraints;
drop table DYEXTN_STRING_TYPE_INFO cascade constraints;
drop table DYEXTN_TABLE_PROPERTIES cascade constraints;
drop table DYEXTN_TAGGED_VALUE cascade constraints;
drop table DYEXTN_TEXTAREA cascade constraints;
drop table DYEXTN_TEXTFIELD cascade constraints;
drop table DYEXTN_USERDEFINED_DE cascade constraints;
drop table DYEXTN_USERDEF_DE_VALUE_REL cascade constraints;
drop table DYEXTN_VIEW cascade constraints;
drop table PATH cascade constraints;
drop table dyextn_id_generator cascade constraints;
drop sequence ABSTRACT_CATEGORY_SEQ;
drop sequence CONSTRAINT_SEQ;
drop sequence CURATED_PATH_SEQ;
drop sequence DE_ATTR_REC_SEQ;
drop sequence DE_COLL_ATTR_REC_VALUES_SEQ;
drop sequence DE_FILE_ATTR_REC_VALUES_SEQ;
drop sequence DE_OBJECT_ATTR_REC_VALUES_SEQ;
drop sequence DYEXTN_ABSTRACT_FRM_CTXT_SEQ;
drop sequence DYEXTN_ABSTRACT_METADATA_SEQ;
drop sequence DYEXTN_ABSTRACT_RE_SEQ;
drop sequence DYEXTN_ABSTR_CAT_ATTR_SEQ;
drop sequence DYEXTN_ASSO_DISPLAY_ATTR_SEQ;
drop sequence DYEXTN_CNSTRKEY_PROP_SEQ;
drop sequence DYEXTN_CONTAINER_SEQ;
drop sequence DYEXTN_CONTROL_SEQ;
drop sequence DYEXTN_DATABASE_PROPERTIES_SEQ;
drop sequence DYEXTN_DATA_ELEMENT_SEQ;
drop sequence DYEXTN_DE_AUDIT_SEQ;
drop sequence DYEXTN_FILE_EXTN_SEQ;
drop sequence DYEXTN_FORMULA_SEQ;
drop sequence DYEXTN_FRM_CONTROL_SEQ;
drop sequence DYEXTN_PATH_ASSO_REL_SEQ;
drop sequence DYEXTN_PATH_SEQ;
drop sequence DYEXTN_PERMISSIBLEVAL_SEQ;
drop sequence DYEXTN_ROLE_SEQ;
drop sequence DYEXTN_RULE_PARAMETER_SEQ;
drop sequence DYEXTN_RULE_SEQ;
drop sequence DYEXTN_SEMANTIC_PROPERTY_SEQ;
drop sequence DYEXTN_TAGGED_VALUE_SEQ;
drop sequence DYEXTN_VALUE_DOMAIN_SEQ;
drop sequence DYEXTN_VIEW_SEQ;
drop sequence DYEX_ATTR_TYP_INFO_SEQ;
drop sequence PATH_SEQ;
create table ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER number(19,0) not null, ABSTRACT_CATEGORY_ID number(19,0), PARENT_CATEGORIAL_CLASS_ID number(19,0), PATH_FROM_PARENT_ID number(19,0), DE_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table ABSTRACT_CATEGORY (ID number(19,0) not null, PARENT_CATEGORY_ID number(19,0) unique, primary key (ID));
create table CATEGORIAL_ATTRIBUTE (ID number(19,0) not null, DE_CATEGORY_ATTRIBUTE_ID number(19,0), primary key (ID));
create table CATEGORIAL_CLASS (ID number(19,0) not null, primary key (ID));
create table CATEGORY (ID number(19,0) not null, DE_ENTITY_ID number(19,0), ROOT_CLASS_ID number(19,0) unique, primary key (ID));
create table CURATED_PATH (CURATED_PATH_ID number(19,0) not null, ENTITY_IDS varchar2(30 char), SELECTED number(1,0), primary key (CURATED_PATH_ID));
create table CURATED_PATH_TO_PATH (CURATED_PATH_ID number(19,0) not null, PATH_ID number(19,0) not null, primary key (CURATED_PATH_ID, PATH_ID));
create table DE_COLL_ATTR_RECORD_VALUES (IDENTIFIER number(19,0) not null, RECORD_VALUE varchar2(4000 char), COLLECTION_ATTR_RECORD_ID number(19,0), primary key (IDENTIFIER));
create table DE_FILE_ATTR_RECORD_VALUES (IDENTIFIER number(19,0) not null, CONTENT_TYPE varchar2(255 char), FILE_CONTENT blob, FILE_NAME varchar2(255 char), RECORD_ID number(19,0), primary key (IDENTIFIER));
create table DE_OBJECT_ATTR_RECORD_VALUES (IDENTIFIER number(19,0) not null, CLASS_NAME varchar2(255 char), OBJECT_CONTENT blob, RECORD_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_ENTITY (id number(19,0) not null, primary key (id));
create table DYEXTN_ABSTRACT_FORM_CONTEXT (IDENTIFIER number(19,0) not null, FORM_LABEL varchar2(255 char), ACTIVITY_STATUS varchar2(10 char), HIDE_FORM number(1,0), CONTAINER_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_METADATA (IDENTIFIER number(19,0) not null, CREATED_DATE date, DESCRIPTION varchar2(1000 char), LAST_UPDATED date, NAME varchar2(1000 char), PUBLIC_ID varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_RECORD_ENTRY (IDENTIFIER number(19,0) not null, ABSTRACT_FORM_CONTEXT_ID number(19,0), ACTIVITY_STATUS varchar2(10 char), MODIFIED_BY varchar2(255 char), MODIFIED_DATE date, primary key (IDENTIFIER));
create table DYEXTN_ABSTR_CAT_ATTR (ID number(19,0) not null, CATEGORIAL_CLASS_ID number(19,0), DE_SOURCE_CLASS_ATTRIBUTE_ID number(19,0), ABSTR_CATEGORIAL_ATTRIBUTE_ID number(19,0), primary key (ID));
create table DYEXTN_ABSTR_CONTAIN_CTR (IDENTIFIER number(19,0) not null, CONTAINER_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ASSOCIATION (IDENTIFIER number(19,0) not null, IS_COLLECTION number(1,0), DIRECTION varchar2(255 char), TARGET_ENTITY_ID number(19,0), SOURCE_ROLE_ID number(19,0), TARGET_ROLE_ID number(19,0), IS_SYSTEM_GENERATED number(1,0), primary key (IDENTIFIER));
create table DYEXTN_ASSO_DISPLAY_ATTR (IDENTIFIER number(19,0) not null, SEQUENCE_NUMBER number(10,0), DISPLAY_ATTRIBUTE_ID number(19,0), SELECT_CONTROL_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE (IDENTIFIER number(19,0) not null, ENTIY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE_RECORD (IDENTIFIER number(19,0) not null, ENTITY_ID number(19,0), ATTRIBUTE_ID number(19,0), RECORD_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER number(19,0) not null, PRIMITIVE_ATTRIBUTE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_BARR_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_BOOLEAN_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE number(1,0), primary key (IDENTIFIER));
create table DYEXTN_BOOLEAN_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_BYTE_ARRAY_TYPE_INFO (IDENTIFIER number(19,0) not null, CONTENT_TYPE varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_CADSRDE (IDENTIFIER number(19,0) not null, PUBLIC_ID varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_CADSR_VALUE_DOMAIN_INFO (IDENTIFIER number(19,0) not null, DATATYPE varchar2(255 char), NAME varchar2(255 char), TYPE varchar2(255 char), PRIMITIVE_ATTRIBUTE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CALCULATED_ATTRIBUTE (IDENTIFIER number(19,0) not null, SOURCE_CAT_ATTR_ID number(19,0), TARGET_CAL_ATTR_ID number(19,0), CAL_CATEGORY_ATTR_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CATEGORY (IDENTIFIER number(19,0) not null, USER_ID number(19,0), ROOT_CATEGORY_ELEMENT number(19,0), CATEGORY_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ASSOCIATION (IDENTIFIER number(19,0) not null, CATEGORY_ENTIY_ID number(19,0), CATEGORY_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER number(19,0) not null, ABSTRACT_ATTRIBUTE_ID number(19,0), CATEGORY_ENTIY_ID number(19,0), IS_VISIBLE number(1,0), IS_RELATTRIBUTE number(1,0), IS_CAL_ATTRIBUTE number(1,0), IS_SRC_FOR_CAL_ATTR number(1,0), IS_SKIP_LOGIC number(1,0), CAL_CATEGORY_ATTR_ID number(19,0), CAL_DEPENDENT_CATEGORY_ATTR_ID number(19,0), CATEGORY_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ENTITY (IDENTIFIER number(19,0) not null, NUMBER_OF_ENTRIES number(10,0), ENTITY_ID number(19,0), OWN_PARENT_CATEGORY_ENTITY_ID number(19,0), TREE_PARENT_CATEGORY_ENTITY_ID number(19,0), IS_CREATETABLE number(1,0), REL_ATTR_CAT_ENTITY_ID number(19,0), CATEGORY_ASSOCIATION_ID number(19,0), PARENT_CATEGORY_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CAT_ASSO_CTL (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_CHECK_BOX (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_COLUMN_PROPERTIES (IDENTIFIER number(19,0) not null, PRIMITIVE_ATTRIBUTE_ID number(19,0), CATEGORY_ATTRIBUTE_ID number(19,0), CNSTR_KEY_PROP_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_COMBOBOX (IDENTIFIER number(19,0) not null, NO_OF_COLUMNS number(10,0), primary key (IDENTIFIER));
create table DYEXTN_CONSTRAINTKEY_PROP (IDENTIFIER number(19,0) not null, PRIMARY_ATTRIBUTE_ID number(19,0), SRC_CONSTRAINT_KEY_ID number(19,0), TGT_CONSTRAINT_KEY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CONSTRAINT_PROPERTIES (IDENTIFIER number(19,0) not null, CONSTRAINT_NAME varchar2(255 char), ASSOCIATION_ID number(19,0), CATEGORY_ASSOCIATION_ID number(19,0), ABSTRACT_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CONTAINER (IDENTIFIER number(19,0) not null, BUTTON_CSS varchar2(255 char), CAPTION varchar2(800 char), ABSTRACT_ENTITY_ID number(19,0), MAIN_TABLE_CSS varchar2(255 char), REQUIRED_FIELD_INDICATOR varchar2(255 char), REQUIRED_FIELD_WARNING_MESSAGE varchar2(255 char), TITLE_CSS varchar2(255 char), BASE_CONTAINER_ID number(19,0), ADD_CAPTION number(1,0), ENTITY_GROUP_ID number(19,0), PARENT_CONTAINER_ID number(19,0), VIEW_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_CONTAINMENT_CONTROL (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_CONTROL (IDENTIFIER number(19,0) not null, SHOW_LABEL number(1,0), CAPTION varchar2(800 char), IS_CALCULATED number(1,0), CSS_CLASS varchar2(255 char), HIDDEN number(1,0), NAME varchar2(255 char), SEQUENCE_NUMBER number(10,0), TOOLTIP varchar2(255 char), CONTAINER_ID number(19,0), BASE_ABST_ATR_ID number(19,0), READ_ONLY number(1,0), SKIP_LOGIC number(1,0), HEADING varchar2(255 char), yPosition number(10,0), SKIP_LOGIC_TARGET_CONTROL number(1,0), SOURCE_CONTROL_ID number(19,0), SHOW_HIDE number(1,0), SELECTIVE_READ_ONLY number(1,0), primary key (IDENTIFIER));
create table DYEXTN_DATABASE_PROPERTIES (IDENTIFIER number(19,0) not null, NAME varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_DATA_ELEMENT (IDENTIFIER number(19,0) not null, CATEGORY_ATTRIBUTE_ID number(19,0), SKIP_LOGIC_ATTRIBUTE_ID number(19,0), ATTRIBUTE_TYPE_INFO_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_DATA_GRID (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_DATEPICKER (IDENTIFIER number(19,0) not null, SHOWCALENDAR number(1,0), DATE_VALUE_TYPE varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_DATE_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE timestamp, primary key (IDENTIFIER));
create table DYEXTN_DATE_TYPE_INFO (IDENTIFIER number(19,0) not null, FORMAT varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_DOUBLE_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE double precision, primary key (IDENTIFIER));
create table DYEXTN_DOUBLE_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_ENTITY (IDENTIFIER number(19,0) not null, DATA_TABLE_STATE number(10,0), ENTITY_GROUP_ID number(19,0), IS_ABSTRACT number(1,0), PARENT_ENTITY_ID number(19,0), INHERITANCE_STRATEGY number(10,0), DISCRIMINATOR_COLUMN_NAME varchar2(255 char), DISCRIMINATOR_VALUE varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_ENTITY_GROUP (IDENTIFIER number(19,0) not null, LONG_NAME varchar2(255 char), SHORT_NAME varchar2(255 char), VERSION varchar2(255 char), IS_SYSTEM_GENERATED number(1,0), primary key (IDENTIFIER));
create table DYEXTN_ENTIY_COMPOSITE_KEY_REL (ENTITY_ID number(19,0) not null, ATTRIBUTE_ID number(19,0) not null, INSERTION_ORDER number(10,0) not null, primary key (ENTITY_ID, INSERTION_ORDER));
create table DYEXTN_FILE_EXTENSIONS (IDENTIFIER number(19,0) not null, FILE_EXTENSION varchar2(255 char), ATTRIBUTE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_FILE_TYPE_INFO (IDENTIFIER number(19,0) not null, MAX_FILE_SIZE float, primary key (IDENTIFIER));
create table DYEXTN_FILE_UPLOAD (IDENTIFIER number(19,0) not null, NO_OF_COLUMNS number(10,0), primary key (IDENTIFIER));
create table DYEXTN_FLOAT_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE float, primary key (IDENTIFIER));
create table DYEXTN_FLOAT_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_FORMULA (IDENTIFIER number(19,0) not null, EXPRESSION varchar2(255 char), CATEGORY_ATTRIBUTE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_FORM_CTRL_NOTES (IDENTIFIER number(19,0) not null, NOTE varchar2(255 char), FORM_CONTROL_ID number(19,0), INSERTION_ORDER number(10,0), primary key (IDENTIFIER));
create table DYEXTN_INTEGER_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE number(10,0), primary key (IDENTIFIER));
create table DYEXTN_INTEGER_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_LABEL (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_LIST_BOX (IDENTIFIER number(19,0) not null, NO_OF_ROWS number(10,0), MULTISELECT number(1,0), USE_AUTOCOMPLETE number(1,0), primary key (IDENTIFIER));
create table DYEXTN_LONG_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE number(19,0), primary key (IDENTIFIER));
create table DYEXTN_LONG_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_MULTISELECT_CHECK_BOX (IDENTIFIER number(19,0) not null, MULTISELECT number(1,0), primary key (IDENTIFIER));
create table DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER number(19,0) not null, MEASUREMENT_UNITS varchar2(255 char), DECIMAL_PLACES number(10,0), NO_DIGITS number(10,0), primary key (IDENTIFIER));
create table DYEXTN_OBJECT_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_PATH (IDENTIFIER number(19,0) not null, CATEGORY_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_PATH_ASSO_REL (IDENTIFIER number(19,0) not null, PATH_ID number(19,0), ASSOCIATION_ID number(19,0), PATH_SEQUENCE_NUMBER number(10,0), SRC_INSTANCE_ID number(19,0), TGT_INSTANCE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER number(19,0) not null, DESCRIPTION varchar2(255 char), CATEGORY_ATTRIBUTE_ID number(19,0), SKIP_LOGIC_CAT_ATTR_ID number(19,0), SKIP_LOGIC_ATTRIBUTE_ID number(19,0), ATTRIBUTE_TYPE_INFO_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER number(19,0) not null, IS_IDENTIFIED number(1,0), IS_PRIMARY_KEY number(1,0), IS_NULLABLE number(1,0), primary key (IDENTIFIER));
create table DYEXTN_RADIOBUTTON (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_ROLE (IDENTIFIER number(19,0) not null, ASSOCIATION_TYPE varchar2(255 char), MAX_CARDINALITY number(10,0), MIN_CARDINALITY number(10,0), NAME varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_RULE (IDENTIFIER number(19,0) not null, NAME varchar2(255 char), IS_IMPLICIT number(1,0), ATTRIBUTE_ID number(19,0), CATEGORY_ATTR_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_RULE_PARAMETER (IDENTIFIER number(19,0) not null, NAME varchar2(255 char), VALUE varchar2(255 char), RULE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_SELECT_CONTROL (IDENTIFIER number(19,0) not null, SEPARATOR_STRING varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_SEMANTIC_PROPERTY (IDENTIFIER number(19,0) not null, CONCEPT_CODE varchar2(255 char), TERM varchar2(255 char), THESAURAS_NAME varchar2(255 char), SEQUENCE_NUMBER number(10,0), CONCEPT_DEFINITION varchar2(255 char), ABSTRACT_METADATA_ID number(19,0), ABSTRACT_VALUE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_SHORT_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE number(5,0), primary key (IDENTIFIER));
create table DYEXTN_SHORT_TYPE_INFO (IDENTIFIER number(19,0) not null, primary key (IDENTIFIER));
create table DYEXTN_SKIP_LOGIC_ATTRIBUTE (IDENTIFIER number(19,0) not null, SOURCE_SKIP_LOGIC_ID number(19,0), TARGET_SKIP_LOGIC_ID number(19,0), CAT_ATTR_ID number(19,0), PERM_VALUE_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_SQL_AUDIT (IDENTIFIER number(19,0) not null, AUDIT_DATE timestamp, QUERY_EXECUTED varchar2(4000 char), USER_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_STRING_CONCEPT_VALUE (IDENTIFIER number(19,0) not null, VALUE varchar2(255 char), primary key (IDENTIFIER));
create table DYEXTN_STRING_TYPE_INFO (IDENTIFIER number(19,0) not null, MAX_SIZE number(10,0), primary key (IDENTIFIER));
create table DYEXTN_TABLE_PROPERTIES (IDENTIFIER number(19,0) not null, ABSTRACT_ENTITY_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_TAGGED_VALUE (IDENTIFIER number(19,0) not null, T_KEY varchar2(255 char), T_VALUE varchar2(255 char), ABSTRACT_METADATA_ID number(19,0), primary key (IDENTIFIER));
create table DYEXTN_TEXTAREA (IDENTIFIER number(19,0) not null, TEXTAREA_COLUMNS number(10,0), TEXTAREA_ROWS number(10,0), primary key (IDENTIFIER));
create table DYEXTN_TEXTFIELD (IDENTIFIER number(19,0) not null, NO_OF_COLUMNS number(10,0), IS_PASSWORD number(1,0), IS_URL number(1,0), primary key (IDENTIFIER));
create table DYEXTN_USERDEFINED_DE (IDENTIFIER number(19,0) not null, IS_ORDERED number(1,0), primary key (IDENTIFIER));
create table DYEXTN_USERDEF_DE_VALUE_REL (USER_DEF_DE_ID number(19,0) not null, PERMISSIBLE_VALUE_ID number(19,0) not null, primary key (USER_DEF_DE_ID, PERMISSIBLE_VALUE_ID));
create table DYEXTN_VIEW (IDENTIFIER number(19,0) not null, NAME varchar2(255 char), primary key (IDENTIFIER));
create table PATH (PATH_ID number(19,0) not null, FIRST_ENTITY_ID number(19,0), LAST_ENTITY_ID number(19,0), INTERMEDIATE_PATH varchar2(150 char), primary key (PATH_ID));
create table dyextn_id_generator (id number(19,0) not null, next_available_id number(19,0), primary key (id));
alter table ABSTRACT_CATEGORIAL_CLASS add constraint FK6C8779AF8168C18B foreign key (PARENT_CATEGORIAL_CLASS_ID) references ABSTRACT_CATEGORIAL_CLASS;
alter table ABSTRACT_CATEGORIAL_CLASS add constraint FK6C8779AF1E10D264 foreign key (ABSTRACT_CATEGORY_ID) references ABSTRACT_CATEGORY;
alter table ABSTRACT_CATEGORY add constraint FK92BB047B70295EEC foreign key (PARENT_CATEGORY_ID) references ABSTRACT_CATEGORY;
alter table CATEGORIAL_ATTRIBUTE add constraint FK31F77B5634ED55B7 foreign key (ID) references DYEXTN_ABSTR_CAT_ATTR;
alter table CATEGORIAL_CLASS add constraint FK9651EF32F94A5493 foreign key (ID) references ABSTRACT_CATEGORIAL_CLASS;
alter table CATEGORY add constraint FK31A8ACFEC88316F9 foreign key (ROOT_CLASS_ID) references CATEGORIAL_CLASS;
alter table CATEGORY add constraint FK31A8ACFEA2330820 foreign key (ID) references ABSTRACT_CATEGORY;
alter table CURATED_PATH_TO_PATH add constraint FK9D8A323C20A0CA98 foreign key (PATH_ID) references PATH;
alter table CURATED_PATH_TO_PATH add constraint FK9D8A323C7D782761 foreign key (CURATED_PATH_ID) references CURATED_PATH;
alter table DE_COLL_ATTR_RECORD_VALUES add constraint FK847DA57775255CA5 foreign key (COLLECTION_ATTR_RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DE_FILE_ATTR_RECORD_VALUES add constraint FKE68334E74EB991B2 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DE_OBJECT_ATTR_RECORD_VALUES add constraint FK504EADC44EB991B2 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD;
alter table DYEXTN_ABSTRACT_ENTITY add constraint FKA4A164E3D3027A30 foreign key (id) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_ABSTRACT_RECORD_ENTRY add constraint FKA74A5FE4DDFB1974 foreign key (ABSTRACT_FORM_CONTEXT_ID) references DYEXTN_ABSTRACT_FORM_CONTEXT;
alter table DYEXTN_ABSTR_CAT_ATTR add constraint FK144CAB469195652D foreign key (ABSTR_CATEGORIAL_ATTRIBUTE_ID) references ABSTRACT_CATEGORIAL_CLASS;
alter table DYEXTN_ABSTR_CAT_ATTR add constraint FK144CAB46A5F024A0 foreign key (CATEGORIAL_CLASS_ID) references ABSTRACT_CATEGORIAL_CLASS;
alter table DYEXTN_ABSTR_CONTAIN_CTR add constraint FK9EB9020A40F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_ABSTR_CONTAIN_CTR add constraint FK9EB9020A69935DD6 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_ASSOCIATION add constraint FK1046842439780F7A foreign key (SOURCE_ROLE_ID) references DYEXTN_ROLE;
alter table DYEXTN_ASSOCIATION add constraint FK104684242BD842F0 foreign key (TARGET_ROLE_ID) references DYEXTN_ROLE;
alter table DYEXTN_ASSOCIATION add constraint FK1046842440738A50 foreign key (TARGET_ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ASSOCIATION add constraint FK104684246D19A21F foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_ASSO_DISPLAY_ATTR add constraint FKD12FD3827FD29CDD foreign key (SELECT_CONTROL_ID) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_ASSO_DISPLAY_ATTR add constraint FKD12FD38235D6E973 foreign key (DISPLAY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_ATTRIBUTE add constraint FK37F1E2FFF99EA906 foreign key (ENTIY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ATTRIBUTE add constraint FK37F1E2FF5CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_ATTRIBUTE_RECORD add constraint FK9B20ED914AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ATTRIBUTE_RECORD add constraint FK9B20ED914DC2CD16 foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_ATTRIBUTE_TYPE_INFO add constraint FK62596D531333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_BARR_CONCEPT_VALUE add constraint FK89D27DF74641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_BASE_ABSTRACT_ATTRIBUTE add constraint FK14BA6610728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_BOOLEAN_CONCEPT_VALUE add constraint FK57B6C4A64641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_BOOLEAN_TYPE_INFO add constraint FK28F1809FE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_BYTE_ARRAY_TYPE_INFO add constraint FK18BDA73E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_CADSRDE add constraint FK588A250953CC4A77 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
alter table DYEXTN_CADSR_VALUE_DOMAIN_INFO add constraint FK1C9AA3641333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_CALCULATED_ATTRIBUTE add constraint FK8D70ECD8B314DD24 foreign key (TARGET_CAL_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_CALCULATED_ATTRIBUTE add constraint FK8D70ECD8BDAACCB6 foreign key (SOURCE_CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_CALCULATED_ATTRIBUTE add constraint FK8D70ECD85CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_CALCULATED_ATTRIBUTE add constraint FK8D70ECD85697A453 foreign key (CAL_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_CATEGORY add constraint FKD33DE81B54A9F59D foreign key (ROOT_CATEGORY_ELEMENT) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY add constraint FKD33DE81B728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_CATEGORY add constraint FKD33DE81B854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ASSOCIATION add constraint FK1B7C663DCAC769C5 foreign key (CATEGORY_ENTIY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ASSOCIATION add constraint FK1B7C663D5CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_CATEGORY_ASSOCIATION add constraint FK1B7C663D854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B7758A2CA8853 foreign key (CAL_DEPENDENT_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B7758CAC769C5 foreign key (CATEGORY_ENTIY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B77587769A811 foreign key (ABSTRACT_ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B77585CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B7758854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ATTRIBUTE add constraint FKEF3B77585697A453 foreign key (CAL_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887FB6EB979 foreign key (CATEGORY_ASSOCIATION_ID) references DYEXTN_CATEGORY_ASSOCIATION;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887D06EE657 foreign key (OWN_PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887A52559D0 foreign key (PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887743AC3F2 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_ENTITY;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA8874AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887F5A32608 foreign key (REL_ATTR_CAT_ENTITY_ID) references DYEXTN_CATEGORY;
alter table DYEXTN_CATEGORY_ENTITY add constraint FK9F2DA887A8103C6F foreign key (TREE_PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_CAT_ASSO_CTL add constraint FK281FAB50C45A8CFA foreign key (IDENTIFIER) references DYEXTN_ABSTR_CONTAIN_CTR;
alter table DYEXTN_CHECK_BOX add constraint FK4EFF925740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3F67F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3F4953F037 foreign key (CNSTR_KEY_PROP_ID) references DYEXTN_CONSTRAINTKEY_PROP;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3F3AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_COLUMN_PROPERTIES add constraint FK8FCE2B3F1333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_COMBOBOX add constraint FKABBC649ABF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511D6B558E0E foreign key (SRC_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES;
alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511D2C4ACB4B foreign key (TGT_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES;
alter table DYEXTN_CONSTRAINTKEY_PROP add constraint FK80C9511DF3077C33 foreign key (PRIMARY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD8FB6EB979 foreign key (CATEGORY_ASSOCIATION_ID) references DYEXTN_CATEGORY_ASSOCIATION;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD87EE87FF6 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD83AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_CONSTRAINT_PROPERTIES add constraint FK82886CD81DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E488C075EF foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E440FCA34B foreign key (PARENT_CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E4BF901C84 foreign key (BASE_CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E41DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY;
alter table DYEXTN_CONTAINER add constraint FK1EAB84E4178865E foreign key (VIEW_ID) references DYEXTN_VIEW;
alter table DYEXTN_CONTAINMENT_CONTROL add constraint FK3F9D4AD3C45A8CFA foreign key (IDENTIFIER) references DYEXTN_ABSTR_CONTAIN_CTR;
alter table DYEXTN_CONTROL add constraint FK70FB5E807792A78F foreign key (BASE_ABST_ATR_ID) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_CONTROL add constraint FK70FB5E80FEA07DFA foreign key (SOURCE_CONTROL_ID) references DYEXTN_CONTROL;
alter table DYEXTN_CONTROL add constraint FK70FB5E8069935DD6 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER;
alter table DYEXTN_DATA_ELEMENT add constraint FKB1153E4791A6280 foreign key (SKIP_LOGIC_ATTRIBUTE_ID) references DYEXTN_SKIP_LOGIC_ATTRIBUTE;
alter table DYEXTN_DATA_ELEMENT add constraint FKB1153E4AA208204 foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_DATA_ELEMENT add constraint FKB1153E467F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_DATA_GRID add constraint FK233EB73E40F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_DATEPICKER add constraint FKFEADD19940F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_DATE_CONCEPT_VALUE add constraint FK45F598A64641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_DATE_TYPE_INFO add constraint FKFBA549FE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_DOUBLE_CONCEPT_VALUE add constraint FKB94E64494641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_DOUBLE_TYPE_INFO add constraint FKC83869C2BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_ENTITY add constraint FK8B24364088C075EF foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP;
alter table DYEXTN_ENTITY add constraint FK8B2436402264D629 foreign key (PARENT_ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ENTITY add constraint FK8B243640743AC3F2 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_ENTITY;
alter table DYEXTN_ENTITY_GROUP add constraint FK105DE7A0728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add constraint FKB3AA6FE04AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY;
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add constraint FKB3AA6FE04DC2CD16 foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE;
alter table DYEXTN_FILE_EXTENSIONS add constraint FKD49834FA56AF0834 foreign key (ATTRIBUTE_ID) references DYEXTN_FILE_TYPE_INFO;
alter table DYEXTN_FILE_TYPE_INFO add constraint FKA00F0EDE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_FILE_UPLOAD add constraint FK2FAD41E740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_FLOAT_CONCEPT_VALUE add constraint FK6785309A4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_FLOAT_TYPE_INFO add constraint FK7E1C0693BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_FORMULA add constraint FKFE34A8967F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_FORM_CTRL_NOTES add constraint FK7A0DA06B41D885B1 foreign key (FORM_CONTROL_ID) references DYEXTN_CONTROL;
alter table DYEXTN_INTEGER_CONCEPT_VALUE add constraint FKFBA33B3C4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_INTEGER_TYPE_INFO add constraint FK5F9CB235BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_LABEL add constraint FK787668D740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_LIST_BOX add constraint FK208395A7BF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_LONG_CONCEPT_VALUE add constraint FK3E1A6EF44641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_LONG_TYPE_INFO add constraint FK257281EDBA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_MULTISELECT_CHECK_BOX add constraint FK4312896DBF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL;
alter table DYEXTN_NUMERIC_TYPE_INFO add constraint FK4DEC9544E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_OBJECT_TYPE_INFO add constraint FK74819FB0E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_PATH add constraint FKC26ADC2854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY;
alter table DYEXTN_PATH_ASSO_REL add constraint FK1E1260A580C8F93E foreign key (PATH_ID) references DYEXTN_PATH;
alter table DYEXTN_PATH_ASSO_REL add constraint FK1E1260A57EE87FF6 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E0668894B9 foreign key (SKIP_LOGIC_CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E0791A6280 foreign key (SKIP_LOGIC_ATTRIBUTE_ID) references DYEXTN_SKIP_LOGIC_ATTRIBUTE;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E0AA208204 foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_PERMISSIBLE_VALUE add constraint FK136264E067F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_PRIMITIVE_ATTRIBUTE add constraint FKA9F765C76D19A21F foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_RADIOBUTTON add constraint FK16F5BA9040F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_RULE add constraint FKC27E099F8DDEC02 foreign key (CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_RULE add constraint FKC27E09990F96714 foreign key (ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE;
alter table DYEXTN_RULE_PARAMETER add constraint FK2256736395D4A5AE foreign key (RULE_ID) references DYEXTN_RULE;
alter table DYEXTN_SELECT_CONTROL add constraint FKDFEBB65740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_SEMANTIC_PROPERTY add constraint FKD2A0B5B15EB60E90 foreign key (ABSTRACT_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_SEMANTIC_PROPERTY add constraint FKD2A0B5B19AEB0CA3 foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_SHORT_CONCEPT_VALUE add constraint FKC1945ABA4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_SHORT_TYPE_INFO add constraint FK99540B3BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add constraint FK722F03989F433752 foreign key (SOURCE_SKIP_LOGIC_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add constraint FK722F039889907A48 foreign key (TARGET_SKIP_LOGIC_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add constraint FK722F03985CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add constraint FK722F0398DB856DA foreign key (CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add constraint FK722F0398B96D382 foreign key (PERM_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_STRING_CONCEPT_VALUE add constraint FKADE7D8894641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_STRING_TYPE_INFO add constraint FKDA35FE02E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO;
alter table DYEXTN_TABLE_PROPERTIES add constraint FKE608E0813AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES;
alter table DYEXTN_TABLE_PROPERTIES add constraint FKE608E0811DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY;
alter table DYEXTN_TAGGED_VALUE add constraint FKF79D055B9AEB0CA3 foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA;
alter table DYEXTN_TEXTAREA add constraint FK946EE25740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_TEXTFIELD add constraint FKF9AFC85040F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL;
alter table DYEXTN_USERDEFINED_DE add constraint FK630761FF53CC4A77 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT;
alter table DYEXTN_USERDEF_DE_VALUE_REL add constraint FK3EE58DCF49BDD67 foreign key (PERMISSIBLE_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE;
alter table DYEXTN_USERDEF_DE_VALUE_REL add constraint FK3EE58DCF5521B106 foreign key (USER_DEF_DE_ID) references DYEXTN_USERDEFINED_DE;
create sequence ABSTRACT_CATEGORY_SEQ;
create sequence CONSTRAINT_SEQ;
create sequence CURATED_PATH_SEQ;
create sequence DE_ATTR_REC_SEQ;
create sequence DE_COLL_ATTR_REC_VALUES_SEQ;
create sequence DE_FILE_ATTR_REC_VALUES_SEQ;
create sequence DE_OBJECT_ATTR_REC_VALUES_SEQ;
create sequence DYEXTN_ABSTRACT_FRM_CTXT_SEQ;
create sequence DYEXTN_ABSTRACT_METADATA_SEQ;
create sequence DYEXTN_ABSTRACT_RE_SEQ;
create sequence DYEXTN_ABSTR_CAT_ATTR_SEQ;
create sequence DYEXTN_ASSO_DISPLAY_ATTR_SEQ;
create sequence DYEXTN_CNSTRKEY_PROP_SEQ;
create sequence DYEXTN_CONTAINER_SEQ;
create sequence DYEXTN_CONTROL_SEQ;
create sequence DYEXTN_DATABASE_PROPERTIES_SEQ;
create sequence DYEXTN_DATA_ELEMENT_SEQ;
create sequence DYEXTN_DE_AUDIT_SEQ;
create sequence DYEXTN_FILE_EXTN_SEQ;
create sequence DYEXTN_FORMULA_SEQ;
create sequence DYEXTN_FRM_CONTROL_SEQ;
create sequence DYEXTN_PATH_ASSO_REL_SEQ;
create sequence DYEXTN_PATH_SEQ;
create sequence DYEXTN_PERMISSIBLEVAL_SEQ;
create sequence DYEXTN_ROLE_SEQ;
create sequence DYEXTN_RULE_PARAMETER_SEQ;
create sequence DYEXTN_RULE_SEQ;
create sequence DYEXTN_SEMANTIC_PROPERTY_SEQ;
create sequence DYEXTN_TAGGED_VALUE_SEQ;
create sequence DYEXTN_VALUE_DOMAIN_SEQ;
create sequence DYEXTN_VIEW_SEQ;
create sequence DYEX_ATTR_TYP_INFO_SEQ;
create sequence PATH_SEQ;

DROP TABLE INTER_MODEL_ASSOCIATION CASCADE CONSTRAINTS;
DROP TABLE INTRA_MODEL_ASSOCIATION CASCADE CONSTRAINTS;
DROP TABLE ASSOCIATION CASCADE CONSTRAINTS;

/* Possible values for ASSOCIATION_TYPE are 1 and 2
ASSOCIATION_TYPE = 1 represents INTER_MODEL_ASSOCIATION.
ASSOCIATION_TYPE = 2 represents INTRA_MODEL_ASSOCIATION.
*/
CREATE TABLE ASSOCIATION(
    ASSOCIATION_ID    NUMBER(38,0)    NOT NULL,
    ASSOCIATION_TYPE  NUMBER(8,0)    NOT NULL ,
    PRIMARY KEY (ASSOCIATION_ID)
);

CREATE TABLE INTER_MODEL_ASSOCIATION(
    ASSOCIATION_ID      NUMBER(38,0)  NOT NULL REFERENCES ASSOCIATION(ASSOCIATION_ID),
    LEFT_ENTITY_ID      NUMBER(38,0)  NOT NULL,
    LEFT_ATTRIBUTE_ID   NUMBER(38,0)  NOT NULL,
    RIGHT_ENTITY_ID     NUMBER(38,0)  NOT NULL,
    RIGHT_ATTRIBUTE_ID  NUMBER(38,0)  NOT NULL,
    PRIMARY KEY (ASSOCIATION_ID)
);
CREATE TABLE INTRA_MODEL_ASSOCIATION(
    ASSOCIATION_ID    NUMBER(38,0)    NOT NULL REFERENCES ASSOCIATION(ASSOCIATION_ID),
    DE_ASSOCIATION_ID NUMBER(38,0)    NOT NULL,
    PRIMARY KEY (ASSOCIATION_ID)
);

drop table ID_TABLE CASCADE CONSTRAINTS;

CREATE TABLE ID_TABLE(
    NEXT_ASSOCIATION_ID    NUMBER(38,0)    NOT NULL,
    PRIMARY KEY (NEXT_ASSOCIATION_ID)
);

insert into ID_TABLE(NEXT_ASSOCIATION_ID) values(1);

commit;
