//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 12:38:09 PM GMT+05:30 
//


package edu.common.dynamicextensions.util.xml.formdefinition;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Form element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Form">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}SingleLineDisplay" maxOccurs="unbounded"/>
 *           &lt;element ref="{}Subform" maxOccurs="unbounded"/>
 *           &lt;element ref="{}Instances" minOccurs="0"/>
 *           &lt;element ref="{}SkipLogic" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="show" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "singleLineDisplay",
    "subform",
    "instances",
    "skipLogic"
})
@XmlRootElement(name = "Form")
public class Form {

    @XmlElement(name = "SingleLineDisplay")
    protected List<SingleLineDisplay> singleLineDisplay;
    @XmlElement(name = "Subform")
    protected List<Subform> subform;
    @XmlElement(name = "Instances")
    protected Instances instances;
    @XmlElement(name = "SkipLogic")
    protected SkipLogic skipLogic;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected Boolean show;

    /**
     * Gets the value of the singleLineDisplay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleLineDisplay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleLineDisplay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleLineDisplay }
     * 
     * 
     */
    public List<SingleLineDisplay> getSingleLineDisplay() {
        if (singleLineDisplay == null) {
            singleLineDisplay = new ArrayList<SingleLineDisplay>();
        }
        return this.singleLineDisplay;
    }

    /**
     * Gets the value of the subform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subform }
     * 
     * 
     */
    public List<Subform> getSubform() {
        if (subform == null) {
            subform = new ArrayList<Subform>();
        }
        return this.subform;
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link Instances }
     *     
     */
    public Instances getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instances }
     *     
     */
    public void setInstances(Instances value) {
        this.instances = value;
    }

    /**
     * Gets the value of the skipLogic property.
     * 
     * @return
     *     possible object is
     *     {@link SkipLogic }
     *     
     */
    public SkipLogic getSkipLogic() {
        return skipLogic;
    }

    /**
     * Sets the value of the skipLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkipLogic }
     *     
     */
    public void setSkipLogic(SkipLogic value) {
        this.skipLogic = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShow(Boolean value) {
        this.show = value;
    }

}
