//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 12:38:09 PM GMT+05:30 
//


package edu.common.dynamicextensions.util.xml.formdefinition;

import javax.xml.bind.annotation.XmlRegistry;
import edu.common.dynamicextensions.util.xml.formdefinition.Attribute;
import edu.common.dynamicextensions.util.xml.formdefinition.ControllingAttribute;
import edu.common.dynamicextensions.util.xml.formdefinition.DependentAttribute;
import edu.common.dynamicextensions.util.xml.formdefinition.Form;
import edu.common.dynamicextensions.util.xml.formdefinition.FormDefinition;
import edu.common.dynamicextensions.util.xml.formdefinition.Instance;
import edu.common.dynamicextensions.util.xml.formdefinition.Instances;
import edu.common.dynamicextensions.util.xml.formdefinition.ObjectFactory;
import edu.common.dynamicextensions.util.xml.formdefinition.PermissibleValue;
import edu.common.dynamicextensions.util.xml.formdefinition.Property;
import edu.common.dynamicextensions.util.xml.formdefinition.SingleLineDisplay;
import edu.common.dynamicextensions.util.xml.formdefinition.SkipLogic;
import edu.common.dynamicextensions.util.xml.formdefinition.Subform;
import edu.common.dynamicextensions.util.xml.formdefinition.Subset;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.common.dynamicextensions.util.xml.formdefinition package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.common.dynamicextensions.util.xml.formdefinition
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link PermissibleValue }
     * 
     */
    public PermissibleValue createPermissibleValue() {
        return new PermissibleValue();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Instances }
     * 
     */
    public Instances createInstances() {
        return new Instances();
    }

    /**
     * Create an instance of {@link Subset }
     * 
     */
    public Subset createSubset() {
        return new Subset();
    }

    /**
     * Create an instance of {@link ControllingAttribute }
     * 
     */
    public ControllingAttribute createControllingAttribute() {
        return new ControllingAttribute();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link SkipLogic }
     * 
     */
    public SkipLogic createSkipLogic() {
        return new SkipLogic();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link SingleLineDisplay }
     * 
     */
    public SingleLineDisplay createSingleLineDisplay() {
        return new SingleLineDisplay();
    }

    /**
     * Create an instance of {@link Subform }
     * 
     */
    public Subform createSubform() {
        return new Subform();
    }

    /**
     * Create an instance of {@link FormDefinition }
     * 
     */
    public FormDefinition createFormDefinition() {
        return new FormDefinition();
    }

    /**
     * Create an instance of {@link DependentAttribute }
     * 
     */
    public DependentAttribute createDependentAttribute() {
        return new DependentAttribute();
    }

}
