//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.09.08 at 06:05:35 PM GMT+05:30
//

package edu.common.dynamicextensions.util.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for controls element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="controls">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="control" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;all>
 *                     &lt;element name="common-validation" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="common-validation-rule" maxOccurs="unbounded">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;attribute name="isImplicit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="datatypes" type="{}dataTypeClass" minOccurs="0"/>
 *                   &lt;/all>
 *                   &lt;attribute name="display-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="image-path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="jspName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"control"})
@XmlRootElement(name = "controls")
public class Controls
{

	protected List<Control> control;

	/**
	 * Gets the value of the control property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the control property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getControl().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Control }
	 *
	 *
	 */
	public List<Control> getControl()
	{
		if (control == null)
		{
			control = new ArrayList<Control>();
		}
		return control;
	}

	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;all>
	 *         &lt;element name="common-validation" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="common-validation-rule" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="isImplicit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="datatypes" type="{}dataTypeClass" minOccurs="0"/>
	 *       &lt;/all>
	 *       &lt;attribute name="display-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="image-path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="jspName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {

	})
	public static class Control
	{

		@XmlElement(name = "common-validation")
		protected CommonValidation commonValidation;
		protected DataTypeClass datatypes;
		@XmlAttribute(name = "display-label", required = true)
		protected String displayLabel;
		@XmlAttribute(name = "image-path", required = true)
		protected String imagePath;
		@XmlAttribute(required = true)
		protected String jspName;
		@XmlAttribute(required = true)
		protected String name;

		/**
		 * Gets the value of the commonValidation property.
		 *
		 * @return
		 *     possible object is
		 *     {@link CommonValidation }
		 *
		 */
		public CommonValidation getCommonValidation()
		{
			return commonValidation;
		}

		/**
		 * Sets the value of the commonValidation property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link CommonValidation }
		 *
		 */
		public void setCommonValidation(CommonValidation value)
		{
			commonValidation = value;
		}

		/**
		 * Gets the value of the datatypes property.
		 *
		 * @return
		 *     possible object is
		 *     {@link DataTypeClass }
		 *
		 */
		public DataTypeClass getDatatypes()
		{
			return datatypes;
		}

		/**
		 * Sets the value of the datatypes property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link DataTypeClass }
		 *
		 */
		public void setDatatypes(DataTypeClass value)
		{
			datatypes = value;
		}

		/**
		 * Gets the value of the displayLabel property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getDisplayLabel()
		{
			return displayLabel;
		}

		/**
		 * Sets the value of the displayLabel property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setDisplayLabel(String value)
		{
			displayLabel = value;
		}

		/**
		 * Gets the value of the imagePath property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getImagePath()
		{
			return imagePath;
		}

		/**
		 * Sets the value of the imagePath property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setImagePath(String value)
		{
			imagePath = value;
		}

		/**
		 * Gets the value of the jspName property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getJspName()
		{
			return jspName;
		}

		/**
		 * Sets the value of the jspName property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setJspName(String value)
		{
			jspName = value;
		}

		/**
		 * Gets the value of the name property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getName()
		{
			return name;
		}

		/**
		 * Sets the value of the name property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setName(String value)
		{
			name = value;
		}

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="common-validation-rule" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="isImplicit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {"commonValidationRule"})
		public static class CommonValidation
		{

			@XmlElement(name = "common-validation-rule")
			protected List<CommonValidationRule> commonValidationRule;

			/**
			 * Gets the value of the commonValidationRule property.
			 *
			 * <p>
			 * This accessor method returns a reference to the live list,
			 * not a snapshot. Therefore any modification you make to the
			 * returned list will be present inside the JAXB object.
			 * This is why there is not a <CODE>set</CODE> method for the commonValidationRule property.
			 *
			 * <p>
			 * For example, to add a new item, do as follows:
			 * <pre>
			 *    getCommonValidationRule().add(newItem);
			 * </pre>
			 *
			 *
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link CommonValidationRule }
			 *
			 *
			 */
			public List<CommonValidationRule> getCommonValidationRule()
			{
				if (commonValidationRule == null)
				{
					commonValidationRule = new ArrayList<CommonValidationRule>();
				}
				return commonValidationRule;
			}

			/**
			 * <p>Java class for anonymous complex type.
			 *
			 * <p>The following schema fragment specifies the expected content contained within this class.
			 *
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="isImplicit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
			 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 *
			 *
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class CommonValidationRule
			{

				@XmlAttribute(required = true)
				protected boolean isImplicit;
				@XmlAttribute(required = true)
				protected String name;

				/**
				 * Gets the value of the isImplicit property.
				 *
				 */
				public boolean isIsImplicit()
				{
					return isImplicit;
				}

				/**
				 * Sets the value of the isImplicit property.
				 *
				 */
				public void setIsImplicit(boolean value)
				{
					isImplicit = value;
				}

				/**
				 * Gets the value of the name property.
				 *
				 * @return
				 *     possible object is
				 *     {@link String }
				 *
				 */
				public String getName()
				{
					return name;
				}

				/**
				 * Sets the value of the name property.
				 *
				 * @param value
				 *     allowed object is
				 *     {@link String }
				 *
				 */
				public void setName(String value)
				{
					name = value;
				}

			}

		}

	}

}
