//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.24 at 07:38:07 PM GMT+05:30 
//

package edu.common.dynamicextensions.util.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2011.01.03 at 05:49:05 PM GMT+05:30 
//

/**
* <p>Java class for FormDefinition element declaration.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;element name="FormDefinition">
*   &lt;complexType>
*     &lt;complexContent>
*       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*         &lt;choice maxOccurs="unbounded" minOccurs="0">
*           &lt;element name="Form">
*             &lt;complexType>
*               &lt;complexContent>
*                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                   &lt;sequence>
*                     &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                     &lt;element name="Tag" maxOccurs="unbounded" minOccurs="0">
*                       &lt;complexType>
*                         &lt;complexContent>
*                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                             &lt;sequence>
*                               &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                               &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                             &lt;/sequence>
*                           &lt;/restriction>
*                         &lt;/complexContent>
*                       &lt;/complexType>
*                     &lt;/element>
*                     &lt;element name="GridView">
*                       &lt;complexType>
*                         &lt;complexContent>
*                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                             &lt;sequence>
*                               &lt;element name="GridDisplayColumn" maxOccurs="unbounded" minOccurs="0">
*                                 &lt;complexType>
*                                   &lt;complexContent>
*                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*                                       &lt;sequence>
*                                         &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                                         &lt;element name="dispalyLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                                         &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
*                                       &lt;/sequence>
*                                     &lt;/restriction>
*                                   &lt;/complexContent>
*                                 &lt;/complexType>
*                               &lt;/element>
*                             &lt;/sequence>
*                           &lt;/restriction>
*                         &lt;/complexContent>
*                       &lt;/complexType>
*                     &lt;/element>
*                     &lt;element name="DataQuery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*                   &lt;/sequence>
*                   &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
*                 &lt;/restriction>
*               &lt;/complexContent>
*             &lt;/complexType>
*           &lt;/element>
*         &lt;/choice>
*       &lt;/restriction>
*     &lt;/complexContent>
*   &lt;/complexType>
* &lt;/element>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "form"
})
@XmlRootElement(name = "FormDefinition")
public class FormDefinition {

 @XmlElement(name = "Form")
 protected List<Form> form;

 /**
  * Gets the value of the form property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the form property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getForm().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link Form }
  * 
  * 
  */
 public List<Form> getForm() {
     if (form == null) {
         form = new ArrayList<Form>();
     }
     return this.form;
 }


 /**
  * <p>Java class for anonymous complex type.
  * 
  * <p>The following schema fragment specifies the expected content contained within this class.
  * 
  * <pre>
  * &lt;complexType>
  *   &lt;complexContent>
  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *       &lt;sequence>
  *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *         &lt;element name="Tag" maxOccurs="unbounded" minOccurs="0">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *         &lt;element name="GridView">
  *           &lt;complexType>
  *             &lt;complexContent>
  *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                 &lt;sequence>
  *                   &lt;element name="GridDisplayColumn" maxOccurs="unbounded" minOccurs="0">
  *                     &lt;complexType>
  *                       &lt;complexContent>
  *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
  *                           &lt;sequence>
  *                             &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *                             &lt;element name="dispalyLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *                             &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
  *                           &lt;/sequence>
  *                         &lt;/restriction>
  *                       &lt;/complexContent>
  *                     &lt;/complexType>
  *                   &lt;/element>
  *                 &lt;/sequence>
  *               &lt;/restriction>
  *             &lt;/complexContent>
  *           &lt;/complexType>
  *         &lt;/element>
  *         &lt;element name="DataQuery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
  *       &lt;/sequence>
  *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
  *     &lt;/restriction>
  *   &lt;/complexContent>
  * &lt;/complexType>
  * </pre>
  * 
  * 
  */
 @XmlAccessorType(XmlAccessType.FIELD)
 @XmlType(name = "", propOrder = {
     "url",
     "tag",
     "gridView",
     "dataQuery"
 })
 public static class Form {

     @XmlElement(name = "Url")
     protected String url;
     @XmlElement(name = "Tag")
     protected List<Tag> tag;
     @XmlElement(name = "GridView")
     protected GridView gridView;
     @XmlElement(name = "DataQuery")
     protected String dataQuery;
     @XmlAttribute
     protected String name;

     /**
      * Gets the value of the url property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getUrl() {
         return url;
     }

     /**
      * Sets the value of the url property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setUrl(String value) {
         this.url = value;
     }

     /**
      * Gets the value of the tag property.
      * 
      * <p>
      * This accessor method returns a reference to the live list,
      * not a snapshot. Therefore any modification you make to the
      * returned list will be present inside the JAXB object.
      * This is why there is not a <CODE>set</CODE> method for the tag property.
      * 
      * <p>
      * For example, to add a new item, do as follows:
      * <pre>
      *    getTag().add(newItem);
      * </pre>
      * 
      * 
      * <p>
      * Objects of the following type(s) are allowed in the list
      * {@link Tag }
      * 
      * 
      */
     public List<Tag> getTag() {
         if (tag == null) {
             tag = new ArrayList<Tag>();
         }
         return this.tag;
     }

     /**
      * Gets the value of the gridView property.
      * 
      * @return
      *     possible object is
      *     {@link GridView }
      *     
      */
     public GridView getGridView() {
         return gridView;
     }

     /**
      * Sets the value of the gridView property.
      * 
      * @param value
      *     allowed object is
      *     {@link GridView }
      *     
      */
     public void setGridView(GridView value) {
         this.gridView = value;
     }

     /**
      * Gets the value of the dataQuery property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getDataQuery() {
         return dataQuery;
     }

     /**
      * Sets the value of the dataQuery property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setDataQuery(String value) {
         this.dataQuery = value;
     }

     /**
      * Gets the value of the name property.
      * 
      * @return
      *     possible object is
      *     {@link String }
      *     
      */
     public String getName() {
         return name;
     }

     /**
      * Sets the value of the name property.
      * 
      * @param value
      *     allowed object is
      *     {@link String }
      *     
      */
     public void setName(String value) {
         this.name = value;
     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="GridDisplayColumn" maxOccurs="unbounded" minOccurs="0">
      *           &lt;complexType>
      *             &lt;complexContent>
      *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *                 &lt;sequence>
      *                   &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      *                   &lt;element name="dispalyLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      *                   &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
      *                 &lt;/sequence>
      *               &lt;/restriction>
      *             &lt;/complexContent>
      *           &lt;/complexType>
      *         &lt;/element>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "gridDisplayColumn"
     })
     public static class GridView {

         @XmlElement(name = "GridDisplayColumn")
         protected List<GridDisplayColumn> gridDisplayColumn;

         /**
          * Gets the value of the gridDisplayColumn property.
          * 
          * <p>
          * This accessor method returns a reference to the live list,
          * not a snapshot. Therefore any modification you make to the
          * returned list will be present inside the JAXB object.
          * This is why there is not a <CODE>set</CODE> method for the gridDisplayColumn property.
          * 
          * <p>
          * For example, to add a new item, do as follows:
          * <pre>
          *    getGridDisplayColumn().add(newItem);
          * </pre>
          * 
          * 
          * <p>
          * Objects of the following type(s) are allowed in the list
          * {@link GridDisplayColumn }
          * 
          * 
          */
         public List<GridDisplayColumn> getGridDisplayColumn() {
             if (gridDisplayColumn == null) {
                 gridDisplayColumn = new ArrayList<GridDisplayColumn>();
             }
             return this.gridDisplayColumn;
         }


         /**
          * <p>Java class for anonymous complex type.
          * 
          * <p>The following schema fragment specifies the expected content contained within this class.
          * 
          * <pre>
          * &lt;complexType>
          *   &lt;complexContent>
          *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
          *       &lt;sequence>
          *         &lt;element name="columnName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
          *         &lt;element name="dispalyLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
          *         &lt;element name="displayOrder" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
          *       &lt;/sequence>
          *     &lt;/restriction>
          *   &lt;/complexContent>
          * &lt;/complexType>
          * </pre>
          * 
          * 
          */
         @XmlAccessorType(XmlAccessType.FIELD)
         @XmlType(name = "", propOrder = {
             "columnName",
             "dispalyLabel",
             "displayOrder"
         })
         public static class GridDisplayColumn {

             protected String columnName;
             protected String dispalyLabel;
             protected Long displayOrder;

             /**
              * Gets the value of the columnName property.
              * 
              * @return
              *     possible object is
              *     {@link String }
              *     
              */
             public String getColumnName() {
                 return columnName;
             }

             /**
              * Sets the value of the columnName property.
              * 
              * @param value
              *     allowed object is
              *     {@link String }
              *     
              */
             public void setColumnName(String value) {
                 this.columnName = value;
             }

             /**
              * Gets the value of the dispalyLabel property.
              * 
              * @return
              *     possible object is
              *     {@link String }
              *     
              */
             public String getDispalyLabel() {
                 return dispalyLabel;
             }

             /**
              * Sets the value of the dispalyLabel property.
              * 
              * @param value
              *     allowed object is
              *     {@link String }
              *     
              */
             public void setDispalyLabel(String value) {
                 this.dispalyLabel = value;
             }

             /**
              * Gets the value of the displayOrder property.
              * 
              * @return
              *     possible object is
              *     {@link Long }
              *     
              */
             public Long getDisplayOrder() {
                 return displayOrder;
             }

             /**
              * Sets the value of the displayOrder property.
              * 
              * @param value
              *     allowed object is
              *     {@link Long }
              *     
              */
             public void setDisplayOrder(Long value) {
                 this.displayOrder = value;
             }

         }

     }


     /**
      * <p>Java class for anonymous complex type.
      * 
      * <p>The following schema fragment specifies the expected content contained within this class.
      * 
      * <pre>
      * &lt;complexType>
      *   &lt;complexContent>
      *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
      *       &lt;sequence>
      *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
      *       &lt;/sequence>
      *     &lt;/restriction>
      *   &lt;/complexContent>
      * &lt;/complexType>
      * </pre>
      * 
      * 
      */
     @XmlAccessorType(XmlAccessType.FIELD)
     @XmlType(name = "", propOrder = {
         "name",
         "value"
     })
     public static class Tag {

         protected String name;
         protected String value;

         /**
          * Gets the value of the name property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getName() {
             return name;
         }

         /**
          * Sets the value of the name property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setName(String value) {
             this.name = value;
         }

         /**
          * Gets the value of the value property.
          * 
          * @return
          *     possible object is
          *     {@link String }
          *     
          */
         public String getValue() {
             return value;
         }

         /**
          * Sets the value of the value property.
          * 
          * @param value
          *     allowed object is
          *     {@link String }
          *     
          */
         public void setValue(String value) {
             this.value = value;
         }

     }

 }

}