//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation
// v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.06.04 at 02:30:58 PM IST
//

package edu.common.dynamicextensions.util.xml;

import javax.xml.bind.annotation.XmlRegistry;

import edu.common.dynamicextensions.util.xml.AttributeType.XmlPermissibleValue;
import edu.common.dynamicextensions.util.xml.Controls.Control;
import edu.common.dynamicextensions.util.xml.Controls.Control.CommonValidation;
import edu.common.dynamicextensions.util.xml.Controls.Control.CommonValidation.CommonValidationRule;
import edu.common.dynamicextensions.util.xml.DataTypeClass.DataType;
import edu.common.dynamicextensions.util.xml.DataTypeClass.DataType.Validations;
import edu.common.dynamicextensions.util.xml.FormDefinition.Form;
import edu.common.dynamicextensions.util.xml.FormDefinition.Form.Tag;
import edu.common.dynamicextensions.util.xml.PropertyType.Option;
import edu.common.dynamicextensions.util.xml.PvVersion.XmlCategory;
import edu.common.dynamicextensions.util.xml.SourceType.QualifierDefinition;
import edu.common.dynamicextensions.util.xml.ValidatorRules.ValidationRule;
import edu.common.dynamicextensions.util.xml.ValidatorRules.ValidationRule.ErrorKey;
import edu.common.dynamicextensions.util.xml.ValidatorRules.ValidationRule.Param;
import edu.common.dynamicextensions.util.xml.XmlPermissibleValues.XmlEntityGroup;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the edu.common.dynamicextensions.util.xml package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 * This class is generated by Jaxb. It is internally by Jaxb while parsing given XML into a POJO.
 * It generates methods depending on the tags of the XML as defined in its XSD.
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: edu.common.dynamicextensions.util.xml
	 *
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link ClassType }
	 *
	 */
	public ClassType createClassType()
	{
		return new ClassType();
	}

	/**
	 * Create an instance of {@link XmlCategory }
	 *
	 */
	public XmlCategory createPvVersionXmlCategory()
	{
		return new XmlCategory();
	}

	/**
	 * Create an instance of {@link XmlAttributeType }
	 *
	 */
	public XmlAttributeType createXmlAttributeType()
	{
		return new XmlAttributeType();
	}

	/**
	 * Create an instance of {@link PvVersion }
	 *
	 */
	public PvVersion createPvVersion()
	{
		return new PvVersion();
	}

	/**
	 * Create an instance of {@link InstanceType }
	 *
	 */
	public InstanceType createInstanceType()
	{
		return new InstanceType();
	}

	/**
	 * Create an instance of {@link PropertyType }
	 *
	 */
	public PropertyType createPropertyType()
	{
		return new PropertyType();
	}

	/**
	 * Create an instance of {@link XmlPermissibleValues }
	 *
	 */
	public XmlPermissibleValues createPvSetTypeXmlPermissibleValues()
	{
		return new XmlPermissibleValues();
	}

	/**
	 * Create an instance of {@link PvSetType }
	 *
	 */
	public PvSetType createPvSetType()
	{
		return new PvSetType();
	}

	/**
	 * Create an instance of {@link Option }
	 *
	 */
	public Option createPropertyTypeOption()
	{
		return new Option();
	}

	//
	// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
	// v2.0-b26-ea3.
	// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
	// Any modifications to this file will be lost upon recompilation of the source schema.
	// Generated on: 2010.07.02 at 12:20:42 PM IST
	//

	/**
	 * This block of Code is generated for Permissible Value XML format.
	 * It is generated By Jaxb to convert Permissible Value XML to POJO
	 *
	 */

	/**
	  * Create an instance of {@link XmlEntityGroup }
	  *
	  */
	public XmlEntityGroup createXmlPermissibleValuesXmlEntityGroup()
	{
		return new XmlEntityGroup();
	}

	/**
	 * Create an instance of {@link QualifierType }
	 *
	 */
	public QualifierType createQualifierType()
	{
		return new QualifierType();
	}

	/**
	 * Create an instance of {@link XmlPermissibleValue }
	 *
	 */
	public XmlPermissibleValue createAttributeTypeXmlPermissibleValue()
	{
		return new XmlPermissibleValue();
	}

	/**
	 * Create an instance of {@link ValueType }
	 *
	 */
	public ValueType createValueType()
	{
		return new ValueType();
	}

	/**
	 * Create an instance of {@link XmlPermissibleValues }
	 *
	 */
	public XmlPermissibleValues createXmlPermissibleValues()
	{
		return new XmlPermissibleValues();
	}

	/**
	 * Create an instance of {@link XmlClassType }
	 *
	 */
	public XmlClassType createXmlClassType()
	{
		return new XmlClassType();
	}

	/**
	 * Create an instance of {@link SourceType }
	 *
	 */
	public SourceType createSourceType()
	{
		return new SourceType();
	}

	/**
	 * Create an instance of {@link QualifierDefinition }
	 *
	 */
	public QualifierDefinition createSourceTypeQualifierDefinition()
	{
		return new QualifierDefinition();
	}

	/**
	 * Create an instance of {@link AttributeType }
	 *
	 */
	public AttributeType createAttributeType()
	{
		return new AttributeType();
	}

	/**
	 * Create an instance of {@link PrimaryDefinitionType }
	 *
	 */
	public PrimaryDefinitionType createPrimaryDefinitionType()
	{
		return new PrimaryDefinitionType();
	}

	//
	// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
	// v2.0-b26-ea3.
	// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
	// Any modifications to this file will be lost upon recompilation of the source schema.
	// Generated on: 2010.07.02 at 12:20:42 PM IST
	//

	/**
	 * This block of Code is generated for Static Form XML format.
	 * It is generated By Jaxb to convert Static Form XML to POJO
	 */

	/**
	 * Create an instance of {@link Tag }.
	 * @return edu.common.dynamicextensions.util.xml.FormDefinition.Form.Tag
	 */
	public Tag createFormDefinitionFormTag()
	{
		return new Tag();
	}

	/**
	 * Create an instance of {@link FormDefinition }.
	 * @return edu.common.dynamicextensions.util.xml.FormDefinition
	 */
	public FormDefinition createFormDefinition()
	{
		return new FormDefinition();
	}

	/**
	 * Create an instance of {@link Form }.
	 * @return edu.common.dynamicextensions.util.xml.FormDefinition.Form
	 */
	public Form createFormDefinitionForm()
	{
		return new Form();
	}

	/**
	 * This object contains factory methods for each
	 * Java content interface and Java element interface
	 * generated in the generated package.
	 * <p>An ObjectFactory allows you to programatically
	 * construct new instances of the Java representation
	 * for XML content. The Java representation of XML
	 * content can consist of schema derived interfaces
	 * and classes representing the binding of schema
	 * type definitions, element declarations and model
	 * groups.  Factory methods for each of these are
	 * provided in this class.
	 *
	 */
	/**
	* Create an instance of {@link Param }
	*
	*/
	public Param createValidatorRulesValidationRuleParam()
	{
		return new Param();
	}

	/**
	 * Create an instance of {@link ValidatorRules }
	 *
	 */
	public ValidatorRules createValidatorRules()
	{
		return new ValidatorRules();
	}

	/**
	 * Create an instance of {@link ErrorKey }
	 *
	 */
	public ErrorKey createValidatorRulesValidationRuleErrorKey()
	{
		return new ErrorKey();
	}

	/**
	 * Create an instance of {@link ValidationRule }
	 *
	 */
	public ValidationRule createValidatorRulesValidationRule()
	{
		return new ValidationRule();
	}

	/**
	 * This object contains factory methods for each
	 * Java content interface and Java element interface
	 * generated in the generated package.
	 * <p>An ObjectFactory allows you to programatically
	 * construct new instances of the Java representation
	 * for XML content. The Java representation of XML
	 * content can consist of schema derived interfaces
	 * and classes representing the binding of schema
	 * type definitions, element declarations and model
	 * groups.  Factory methods for each of these are
	 * provided in this class.
	 *
	 */

	/**
	 * Create an instance of {@link CommonValidation }
	 *
	 */
	public CommonValidation createControlsControlCommonValidation()
	{
		return new CommonValidation();
	}

	/**
	 * Create an instance of {@link DataType }
	 *
	 */
	public DataType createDataTypeClassDataType()
	{
		return new DataType();
	}

	/**
	 * Create an instance of {@link Control }
	 *
	 */
	public Control createControlsControl()
	{
		return new Control();
	}

	/**
	 * Create an instance of {@link Validations }
	 *
	 */
	public Validations createDataTypeClassDataTypeValidations()
	{
		return new Validations();
	}

	/**
	 * Create an instance of {@link ValidationRule }
	 *
	 */
	public ValidationRule createDataTypeClassDataTypeValidationsValidationRule()
	{
		return new ValidationRule();
	}

	/**
	 * Create an instance of {@link Controls }
	 *
	 */
	public Controls createControls()
	{
		return new Controls();
	}

	/**
	 * Create an instance of {@link DataTypeClass }
	 *
	 */
	public DataTypeClass createDataTypeClass()
	{
		return new DataTypeClass();
	}

	/**
	 * Create an instance of {@link CommonValidationRule }
	 *
	 */
	public CommonValidationRule createControlsControlCommonValidationCommonValidationRule()
	{
		return new CommonValidationRule();
	}
}
