alter table ABSTRACT_CATEGORIAL_CLASS drop foreign key FK6C8779AF8168C18B;
alter table ABSTRACT_CATEGORIAL_CLASS drop foreign key FK6C8779AF1E10D264;
alter table ABSTRACT_CATEGORY drop foreign key FK92BB047B70295EEC;
alter table CATEGORIAL_ATTRIBUTE drop foreign key FK31F77B5634ED55B7;
alter table CATEGORIAL_CLASS drop foreign key FK9651EF32F94A5493;
alter table CATEGORY drop foreign key FK31A8ACFEC88316F9;
alter table CATEGORY drop foreign key FK31A8ACFEA2330820;
alter table CURATED_PATH_TO_PATH drop foreign key FK9D8A323C20A0CA98;
alter table CURATED_PATH_TO_PATH drop foreign key FK9D8A323C7D782761;
alter table DE_COLL_ATTR_RECORD_VALUES drop foreign key FK847DA57775255CA5;
alter table DE_FILE_ATTR_RECORD_VALUES drop foreign key FKE68334E74EB991B2;
alter table DE_OBJECT_ATTR_RECORD_VALUES drop foreign key FK504EADC44EB991B2;
alter table DYEXTN_ABSTRACT_ENTITY drop foreign key FKA4A164E3D3027A30;
alter table DYEXTN_ABSTRACT_RECORD_ENTRY drop foreign key FKA74A5FE4DDFB1974;
alter table DYEXTN_ABSTR_CAT_ATTR drop foreign key FK144CAB469195652D;
alter table DYEXTN_ABSTR_CAT_ATTR drop foreign key FK144CAB46A5F024A0;
alter table DYEXTN_ABSTR_CONTAIN_CTR drop foreign key FK9EB9020A40F198C2;
alter table DYEXTN_ABSTR_CONTAIN_CTR drop foreign key FK9EB9020A69935DD6;
alter table DYEXTN_ASSOCIATION drop foreign key FK1046842439780F7A;
alter table DYEXTN_ASSOCIATION drop foreign key FK104684242BD842F0;
alter table DYEXTN_ASSOCIATION drop foreign key FK1046842440738A50;
alter table DYEXTN_ASSOCIATION drop foreign key FK104684246D19A21F;
alter table DYEXTN_ASSO_DISPLAY_ATTR drop foreign key FKD12FD3827FD29CDD;
alter table DYEXTN_ASSO_DISPLAY_ATTR drop foreign key FKD12FD38235D6E973;
alter table DYEXTN_ATTRIBUTE drop foreign key FK37F1E2FFF99EA906;
alter table DYEXTN_ATTRIBUTE drop foreign key FK37F1E2FF5CC8694E;
alter table DYEXTN_ATTRIBUTE_RECORD drop foreign key FK9B20ED914AC41F7E;
alter table DYEXTN_ATTRIBUTE_RECORD drop foreign key FK9B20ED914DC2CD16;
alter table DYEXTN_ATTRIBUTE_TYPE_INFO drop foreign key FK62596D531333996E;
alter table DYEXTN_BARR_CONCEPT_VALUE drop foreign key FK89D27DF74641D513;
alter table DYEXTN_BASE_ABSTRACT_ATTRIBUTE drop foreign key FK14BA6610728B19BE;
alter table DYEXTN_BOOLEAN_CONCEPT_VALUE drop foreign key FK57B6C4A64641D513;
alter table DYEXTN_BOOLEAN_TYPE_INFO drop foreign key FK28F1809FE5294FA3;
alter table DYEXTN_BYTE_ARRAY_TYPE_INFO drop foreign key FK18BDA73E5294FA3;
alter table DYEXTN_CADSRDE drop foreign key FK588A250953CC4A77;
alter table DYEXTN_CADSR_VALUE_DOMAIN_INFO drop foreign key FK1C9AA3641333996E;
alter table DYEXTN_CALCULATED_ATTRIBUTE drop foreign key FK8D70ECD8B314DD24;
alter table DYEXTN_CALCULATED_ATTRIBUTE drop foreign key FK8D70ECD8BDAACCB6;
alter table DYEXTN_CALCULATED_ATTRIBUTE drop foreign key FK8D70ECD85CC8694E;
alter table DYEXTN_CALCULATED_ATTRIBUTE drop foreign key FK8D70ECD85697A453;
alter table DYEXTN_CATEGORY drop foreign key FKD33DE81B54A9F59D;
alter table DYEXTN_CATEGORY drop foreign key FKD33DE81B728B19BE;
alter table DYEXTN_CATEGORY drop foreign key FKD33DE81B854AC01B;
alter table DYEXTN_CATEGORY_ASSOCIATION drop foreign key FK1B7C663DCAC769C5;
alter table DYEXTN_CATEGORY_ASSOCIATION drop foreign key FK1B7C663D5CC8694E;
alter table DYEXTN_CATEGORY_ASSOCIATION drop foreign key FK1B7C663D854AC01B;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B7758A2CA8853;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B7758CAC769C5;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B77587769A811;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B77585CC8694E;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B7758854AC01B;
alter table DYEXTN_CATEGORY_ATTRIBUTE drop foreign key FKEF3B77585697A453;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887FB6EB979;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887D06EE657;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887A52559D0;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887743AC3F2;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA8874AC41F7E;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887F5A32608;
alter table DYEXTN_CATEGORY_ENTITY drop foreign key FK9F2DA887A8103C6F;
alter table DYEXTN_CAT_ASSO_CTL drop foreign key FK281FAB50C45A8CFA;
alter table DYEXTN_CHECK_BOX drop foreign key FK4EFF925740F198C2;
alter table DYEXTN_COLUMN_PROPERTIES drop foreign key FK8FCE2B3F67F8B59;
alter table DYEXTN_COLUMN_PROPERTIES drop foreign key FK8FCE2B3F4953F037;
alter table DYEXTN_COLUMN_PROPERTIES drop foreign key FK8FCE2B3F3AB6A1D3;
alter table DYEXTN_COLUMN_PROPERTIES drop foreign key FK8FCE2B3F1333996E;
alter table DYEXTN_COMBOBOX drop foreign key FKABBC649ABF67AB26;
alter table DYEXTN_CONSTRAINTKEY_PROP drop foreign key FK80C9511D6B558E0E;
alter table DYEXTN_CONSTRAINTKEY_PROP drop foreign key FK80C9511D2C4ACB4B;
alter table DYEXTN_CONSTRAINTKEY_PROP drop foreign key FK80C9511DF3077C33;
alter table DYEXTN_CONSTRAINT_PROPERTIES drop foreign key FK82886CD8FB6EB979;
alter table DYEXTN_CONSTRAINT_PROPERTIES drop foreign key FK82886CD87EE87FF6;
alter table DYEXTN_CONSTRAINT_PROPERTIES drop foreign key FK82886CD83AB6A1D3;
alter table DYEXTN_CONSTRAINT_PROPERTIES drop foreign key FK82886CD81DCC9E63;
alter table DYEXTN_CONTAINER drop foreign key FK1EAB84E488C075EF;
alter table DYEXTN_CONTAINER drop foreign key FK1EAB84E440FCA34B;
alter table DYEXTN_CONTAINER drop foreign key FK1EAB84E4BF901C84;
alter table DYEXTN_CONTAINER drop foreign key FK1EAB84E41DCC9E63;
alter table DYEXTN_CONTAINER drop foreign key FK1EAB84E4178865E;
alter table DYEXTN_CONTAINMENT_CONTROL drop foreign key FK3F9D4AD3C45A8CFA;
alter table DYEXTN_CONTROL drop foreign key FK70FB5E807792A78F;
alter table DYEXTN_CONTROL drop foreign key FK70FB5E80FEA07DFA;
alter table DYEXTN_CONTROL drop foreign key FK70FB5E8069935DD6;
alter table DYEXTN_DATA_ELEMENT drop foreign key FKB1153E4791A6280;
alter table DYEXTN_DATA_ELEMENT drop foreign key FKB1153E4AA208204;
alter table DYEXTN_DATA_ELEMENT drop foreign key FKB1153E467F8B59;
alter table DYEXTN_DATA_GRID drop foreign key FK233EB73E40F198C2;
alter table DYEXTN_DATEPICKER drop foreign key FKFEADD19940F198C2;
alter table DYEXTN_DATE_CONCEPT_VALUE drop foreign key FK45F598A64641D513;
alter table DYEXTN_DATE_TYPE_INFO drop foreign key FKFBA549FE5294FA3;
alter table DYEXTN_DOUBLE_CONCEPT_VALUE drop foreign key FKB94E64494641D513;
alter table DYEXTN_DOUBLE_TYPE_INFO drop foreign key FKC83869C2BA4AE008;
alter table DYEXTN_ENTITY drop foreign key FK8B24364088C075EF;
alter table DYEXTN_ENTITY drop foreign key FK8B2436402264D629;
alter table DYEXTN_ENTITY drop foreign key FK8B243640743AC3F2;
alter table DYEXTN_ENTITY_GROUP drop foreign key FK105DE7A0728B19BE;
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL drop foreign key FKB3AA6FE04AC41F7E;
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL drop foreign key FKB3AA6FE04DC2CD16;
alter table DYEXTN_FILE_EXTENSIONS drop foreign key FKD49834FA56AF0834;
alter table DYEXTN_FILE_TYPE_INFO drop foreign key FKA00F0EDE5294FA3;
alter table DYEXTN_FILE_UPLOAD drop foreign key FK2FAD41E740F198C2;
alter table DYEXTN_FLOAT_CONCEPT_VALUE drop foreign key FK6785309A4641D513;
alter table DYEXTN_FLOAT_TYPE_INFO drop foreign key FK7E1C0693BA4AE008;
alter table DYEXTN_FORMULA drop foreign key FKFE34A8967F8B59;
alter table DYEXTN_FORM_CTRL_NOTES drop foreign key FK7A0DA06B41D885B1;
alter table DYEXTN_INTEGER_CONCEPT_VALUE drop foreign key FKFBA33B3C4641D513;
alter table DYEXTN_INTEGER_TYPE_INFO drop foreign key FK5F9CB235BA4AE008;
alter table DYEXTN_LABEL drop foreign key FK787668D740F198C2;
alter table DYEXTN_LIST_BOX drop foreign key FK208395A7BF67AB26;
alter table DYEXTN_LONG_CONCEPT_VALUE drop foreign key FK3E1A6EF44641D513;
alter table DYEXTN_LONG_TYPE_INFO drop foreign key FK257281EDBA4AE008;
alter table DYEXTN_MULTISELECT_CHECK_BOX drop foreign key FK4312896DBF67AB26;
alter table DYEXTN_NUMERIC_TYPE_INFO drop foreign key FK4DEC9544E5294FA3;
alter table DYEXTN_OBJECT_TYPE_INFO drop foreign key FK74819FB0E5294FA3;
alter table DYEXTN_PATH drop foreign key FKC26ADC2854AC01B;
alter table DYEXTN_PATH_ASSO_REL drop foreign key FK1E1260A580C8F93E;
alter table DYEXTN_PATH_ASSO_REL drop foreign key FK1E1260A57EE87FF6;
alter table DYEXTN_PERMISSIBLE_VALUE drop foreign key FK136264E0668894B9;
alter table DYEXTN_PERMISSIBLE_VALUE drop foreign key FK136264E0791A6280;
alter table DYEXTN_PERMISSIBLE_VALUE drop foreign key FK136264E0AA208204;
alter table DYEXTN_PERMISSIBLE_VALUE drop foreign key FK136264E067F8B59;
alter table DYEXTN_PRIMITIVE_ATTRIBUTE drop foreign key FKA9F765C76D19A21F;
alter table DYEXTN_RADIOBUTTON drop foreign key FK16F5BA9040F198C2;
alter table DYEXTN_RULE drop foreign key FKC27E099F8DDEC02;
alter table DYEXTN_RULE drop foreign key FKC27E09990F96714;
alter table DYEXTN_RULE_PARAMETER drop foreign key FK2256736395D4A5AE;
alter table DYEXTN_SELECT_CONTROL drop foreign key FKDFEBB65740F198C2;
alter table DYEXTN_SEMANTIC_PROPERTY drop foreign key FKD2A0B5B15EB60E90;
alter table DYEXTN_SEMANTIC_PROPERTY drop foreign key FKD2A0B5B19AEB0CA3;
alter table DYEXTN_SHORT_CONCEPT_VALUE drop foreign key FKC1945ABA4641D513;
alter table DYEXTN_SHORT_TYPE_INFO drop foreign key FK99540B3BA4AE008;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE drop foreign key FK722F03989F433752;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE drop foreign key FK722F039889907A48;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE drop foreign key FK722F03985CC8694E;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE drop foreign key FK722F0398DB856DA;
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE drop foreign key FK722F0398B96D382;
alter table DYEXTN_STRING_CONCEPT_VALUE drop foreign key FKADE7D8894641D513;
alter table DYEXTN_STRING_TYPE_INFO drop foreign key FKDA35FE02E5294FA3;
alter table DYEXTN_TABLE_PROPERTIES drop foreign key FKE608E0813AB6A1D3;
alter table DYEXTN_TABLE_PROPERTIES drop foreign key FKE608E0811DCC9E63;
alter table DYEXTN_TAGGED_VALUE drop foreign key FKF79D055B9AEB0CA3;
alter table DYEXTN_TEXTAREA drop foreign key FK946EE25740F198C2;
alter table DYEXTN_TEXTFIELD drop foreign key FKF9AFC85040F198C2;
alter table DYEXTN_USERDEFINED_DE drop foreign key FK630761FF53CC4A77;
alter table DYEXTN_USERDEF_DE_VALUE_REL drop foreign key FK3EE58DCF49BDD67;
alter table DYEXTN_USERDEF_DE_VALUE_REL drop foreign key FK3EE58DCF5521B106;
drop table if exists ABSTRACT_CATEGORIAL_CLASS;
drop table if exists ABSTRACT_CATEGORY;
drop table if exists CATEGORIAL_ATTRIBUTE;
drop table if exists CATEGORIAL_CLASS;
drop table if exists CATEGORY;
drop table if exists CURATED_PATH;
drop table if exists CURATED_PATH_TO_PATH;
drop table if exists DE_COLL_ATTR_RECORD_VALUES;
drop table if exists DE_FILE_ATTR_RECORD_VALUES;
drop table if exists DE_OBJECT_ATTR_RECORD_VALUES;
drop table if exists DYEXTN_ABSTRACT_ENTITY;
drop table if exists DYEXTN_ABSTRACT_FORM_CONTEXT;
drop table if exists DYEXTN_ABSTRACT_METADATA;
drop table if exists DYEXTN_ABSTRACT_RECORD_ENTRY;
drop table if exists DYEXTN_ABSTR_CAT_ATTR;
drop table if exists DYEXTN_ABSTR_CONTAIN_CTR;
drop table if exists DYEXTN_ASSOCIATION;
drop table if exists DYEXTN_ASSO_DISPLAY_ATTR;
drop table if exists DYEXTN_ATTRIBUTE;
drop table if exists DYEXTN_ATTRIBUTE_RECORD;
drop table if exists DYEXTN_ATTRIBUTE_TYPE_INFO;
drop table if exists DYEXTN_BARR_CONCEPT_VALUE;
drop table if exists DYEXTN_BASE_ABSTRACT_ATTRIBUTE;
drop table if exists DYEXTN_BOOLEAN_CONCEPT_VALUE;
drop table if exists DYEXTN_BOOLEAN_TYPE_INFO;
drop table if exists DYEXTN_BYTE_ARRAY_TYPE_INFO;
drop table if exists DYEXTN_CADSRDE;
drop table if exists DYEXTN_CADSR_VALUE_DOMAIN_INFO;
drop table if exists DYEXTN_CALCULATED_ATTRIBUTE;
drop table if exists DYEXTN_CATEGORY;
drop table if exists DYEXTN_CATEGORY_ASSOCIATION;
drop table if exists DYEXTN_CATEGORY_ATTRIBUTE;
drop table if exists DYEXTN_CATEGORY_ENTITY;
drop table if exists DYEXTN_CAT_ASSO_CTL;
drop table if exists DYEXTN_CHECK_BOX;
drop table if exists DYEXTN_COLUMN_PROPERTIES;
drop table if exists DYEXTN_COMBOBOX;
drop table if exists DYEXTN_CONSTRAINTKEY_PROP;
drop table if exists DYEXTN_CONSTRAINT_PROPERTIES;
drop table if exists DYEXTN_CONTAINER;
drop table if exists DYEXTN_CONTAINMENT_CONTROL;
drop table if exists DYEXTN_CONTROL;
drop table if exists DYEXTN_DATABASE_PROPERTIES;
drop table if exists DYEXTN_DATA_ELEMENT;
drop table if exists DYEXTN_DATA_GRID;
drop table if exists DYEXTN_DATEPICKER;
drop table if exists DYEXTN_DATE_CONCEPT_VALUE;
drop table if exists DYEXTN_DATE_TYPE_INFO;
drop table if exists DYEXTN_DOUBLE_CONCEPT_VALUE;
drop table if exists DYEXTN_DOUBLE_TYPE_INFO;
drop table if exists DYEXTN_ENTITY;
drop table if exists DYEXTN_ENTITY_GROUP;
drop table if exists DYEXTN_ENTIY_COMPOSITE_KEY_REL;
drop table if exists DYEXTN_FILE_EXTENSIONS;
drop table if exists DYEXTN_FILE_TYPE_INFO;
drop table if exists DYEXTN_FILE_UPLOAD;
drop table if exists DYEXTN_FLOAT_CONCEPT_VALUE;
drop table if exists DYEXTN_FLOAT_TYPE_INFO;
drop table if exists DYEXTN_FORMULA;
drop table if exists DYEXTN_FORM_CTRL_NOTES;
drop table if exists DYEXTN_INTEGER_CONCEPT_VALUE;
drop table if exists DYEXTN_INTEGER_TYPE_INFO;
drop table if exists DYEXTN_LABEL;
drop table if exists DYEXTN_LIST_BOX;
drop table if exists DYEXTN_LONG_CONCEPT_VALUE;
drop table if exists DYEXTN_LONG_TYPE_INFO;
drop table if exists DYEXTN_MULTISELECT_CHECK_BOX;
drop table if exists DYEXTN_NUMERIC_TYPE_INFO;
drop table if exists DYEXTN_OBJECT_TYPE_INFO;
drop table if exists DYEXTN_PATH;
drop table if exists DYEXTN_PATH_ASSO_REL;
drop table if exists DYEXTN_PERMISSIBLE_VALUE;
drop table if exists DYEXTN_PRIMITIVE_ATTRIBUTE;
drop table if exists DYEXTN_RADIOBUTTON;
drop table if exists DYEXTN_ROLE;
drop table if exists DYEXTN_RULE;
drop table if exists DYEXTN_RULE_PARAMETER;
drop table if exists DYEXTN_SELECT_CONTROL;
drop table if exists DYEXTN_SEMANTIC_PROPERTY;
drop table if exists DYEXTN_SHORT_CONCEPT_VALUE;
drop table if exists DYEXTN_SHORT_TYPE_INFO;
drop table if exists DYEXTN_SKIP_LOGIC_ATTRIBUTE;
drop table if exists DYEXTN_SQL_AUDIT;
drop table if exists DYEXTN_STRING_CONCEPT_VALUE;
drop table if exists DYEXTN_STRING_TYPE_INFO;
drop table if exists DYEXTN_TABLE_PROPERTIES;
drop table if exists DYEXTN_TAGGED_VALUE;
drop table if exists DYEXTN_TEXTAREA;
drop table if exists DYEXTN_TEXTFIELD;
drop table if exists DYEXTN_USERDEFINED_DE;
drop table if exists DYEXTN_USERDEF_DE_VALUE_REL;
drop table if exists DYEXTN_VIEW;
drop table if exists PATH;
drop table if exists dyextn_id_generator;
create table ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER bigint not null auto_increment, ABSTRACT_CATEGORY_ID bigint, PARENT_CATEGORIAL_CLASS_ID bigint, PATH_FROM_PARENT_ID bigint, DE_ENTITY_ID bigint, primary key (IDENTIFIER));
create table ABSTRACT_CATEGORY (ID bigint not null auto_increment, PARENT_CATEGORY_ID bigint unique, primary key (ID));
create table CATEGORIAL_ATTRIBUTE (ID bigint not null, DE_CATEGORY_ATTRIBUTE_ID bigint, primary key (ID));
create table CATEGORIAL_CLASS (ID bigint not null, primary key (ID));
create table CATEGORY (ID bigint not null, DE_ENTITY_ID bigint, ROOT_CLASS_ID bigint unique, primary key (ID));
create table CURATED_PATH (CURATED_PATH_ID bigint not null auto_increment, ENTITY_IDS varchar(30), SELECTED bit, primary key (CURATED_PATH_ID));
create table CURATED_PATH_TO_PATH (CURATED_PATH_ID bigint not null, PATH_ID bigint not null, primary key (CURATED_PATH_ID, PATH_ID));
create table DE_COLL_ATTR_RECORD_VALUES (IDENTIFIER bigint not null auto_increment, RECORD_VALUE text, COLLECTION_ATTR_RECORD_ID bigint, primary key (IDENTIFIER));
create table DE_FILE_ATTR_RECORD_VALUES (IDENTIFIER bigint not null auto_increment, CONTENT_TYPE varchar(255), FILE_CONTENT blob, FILE_NAME varchar(255), RECORD_ID bigint, primary key (IDENTIFIER));
create table DE_OBJECT_ATTR_RECORD_VALUES (IDENTIFIER bigint not null auto_increment, CLASS_NAME varchar(255), OBJECT_CONTENT blob, RECORD_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_ENTITY (id bigint not null, primary key (id));
create table DYEXTN_ABSTRACT_FORM_CONTEXT (IDENTIFIER bigint not null auto_increment, FORM_LABEL varchar(255), ACTIVITY_STATUS varchar(10), HIDE_FORM bit, CONTAINER_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_METADATA (IDENTIFIER bigint not null auto_increment, CREATED_DATE date, DESCRIPTION text, LAST_UPDATED date, NAME text, PUBLIC_ID varchar(255), primary key (IDENTIFIER));
create table DYEXTN_ABSTRACT_RECORD_ENTRY (IDENTIFIER bigint not null auto_increment, ABSTRACT_FORM_CONTEXT_ID bigint, ACTIVITY_STATUS varchar(10), MODIFIED_BY varchar(255), MODIFIED_DATE date, primary key (IDENTIFIER));
create table DYEXTN_ABSTR_CAT_ATTR (ID bigint not null auto_increment, CATEGORIAL_CLASS_ID bigint, DE_SOURCE_CLASS_ATTRIBUTE_ID bigint, ABSTR_CATEGORIAL_ATTRIBUTE_ID bigint, primary key (ID));
create table DYEXTN_ABSTR_CONTAIN_CTR (IDENTIFIER bigint not null, CONTAINER_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ASSOCIATION (IDENTIFIER bigint not null, IS_COLLECTION bit, DIRECTION varchar(255), TARGET_ENTITY_ID bigint, SOURCE_ROLE_ID bigint, TARGET_ROLE_ID bigint, IS_SYSTEM_GENERATED bit, primary key (IDENTIFIER));
create table DYEXTN_ASSO_DISPLAY_ATTR (IDENTIFIER bigint not null auto_increment, SEQUENCE_NUMBER integer, DISPLAY_ATTRIBUTE_ID bigint, SELECT_CONTROL_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE (IDENTIFIER bigint not null, ENTIY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE_RECORD (IDENTIFIER bigint not null auto_increment, ENTITY_ID bigint, ATTRIBUTE_ID bigint, RECORD_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER bigint not null auto_increment, PRIMITIVE_ATTRIBUTE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_BARR_CONCEPT_VALUE (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_BOOLEAN_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE bit, primary key (IDENTIFIER));
create table DYEXTN_BOOLEAN_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_BYTE_ARRAY_TYPE_INFO (IDENTIFIER bigint not null, CONTENT_TYPE varchar(255), primary key (IDENTIFIER));
create table DYEXTN_CADSRDE (IDENTIFIER bigint not null, PUBLIC_ID varchar(255), primary key (IDENTIFIER));
create table DYEXTN_CADSR_VALUE_DOMAIN_INFO (IDENTIFIER bigint not null auto_increment, DATATYPE varchar(255), NAME varchar(255), TYPE varchar(255), PRIMITIVE_ATTRIBUTE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CALCULATED_ATTRIBUTE (IDENTIFIER bigint not null, SOURCE_CAT_ATTR_ID bigint, TARGET_CAL_ATTR_ID bigint, CAL_CATEGORY_ATTR_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CATEGORY (IDENTIFIER bigint not null, USER_ID bigint, ROOT_CATEGORY_ELEMENT bigint, CATEGORY_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ASSOCIATION (IDENTIFIER bigint not null, CATEGORY_ENTIY_ID bigint, CATEGORY_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER bigint not null, ABSTRACT_ATTRIBUTE_ID bigint, CATEGORY_ENTIY_ID bigint, IS_VISIBLE bit, IS_RELATTRIBUTE bit, IS_CAL_ATTRIBUTE bit, IS_SRC_FOR_CAL_ATTR bit, IS_SKIP_LOGIC bit, CAL_CATEGORY_ATTR_ID bigint, CAL_DEPENDENT_CATEGORY_ATTR_ID bigint, CATEGORY_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CATEGORY_ENTITY (IDENTIFIER bigint not null, NUMBER_OF_ENTRIES integer, ENTITY_ID bigint, OWN_PARENT_CATEGORY_ENTITY_ID bigint, TREE_PARENT_CATEGORY_ENTITY_ID bigint, IS_CREATETABLE bit, REL_ATTR_CAT_ENTITY_ID bigint, CATEGORY_ASSOCIATION_ID bigint, PARENT_CATEGORY_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CAT_ASSO_CTL (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_CHECK_BOX (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_COLUMN_PROPERTIES (IDENTIFIER bigint not null, PRIMITIVE_ATTRIBUTE_ID bigint, CATEGORY_ATTRIBUTE_ID bigint, CNSTR_KEY_PROP_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_COMBOBOX (IDENTIFIER bigint not null, NO_OF_COLUMNS integer, primary key (IDENTIFIER));
create table DYEXTN_CONSTRAINTKEY_PROP (IDENTIFIER bigint not null auto_increment, PRIMARY_ATTRIBUTE_ID bigint, SRC_CONSTRAINT_KEY_ID bigint, TGT_CONSTRAINT_KEY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CONSTRAINT_PROPERTIES (IDENTIFIER bigint not null, CONSTRAINT_NAME varchar(255), ASSOCIATION_ID bigint, CATEGORY_ASSOCIATION_ID bigint, ABSTRACT_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CONTAINER (IDENTIFIER bigint not null auto_increment, BUTTON_CSS varchar(255), CAPTION text, ABSTRACT_ENTITY_ID bigint, MAIN_TABLE_CSS varchar(255), REQUIRED_FIELD_INDICATOR varchar(255), REQUIRED_FIELD_WARNING_MESSAGE varchar(255), TITLE_CSS varchar(255), BASE_CONTAINER_ID bigint, ADD_CAPTION bit, ENTITY_GROUP_ID bigint, PARENT_CONTAINER_ID bigint, VIEW_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_CONTAINMENT_CONTROL (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_CONTROL (IDENTIFIER bigint not null auto_increment, SHOW_LABEL bit, CAPTION text, IS_CALCULATED bit, CSS_CLASS varchar(255), HIDDEN bit, NAME varchar(255), SEQUENCE_NUMBER integer, TOOLTIP varchar(255), CONTAINER_ID bigint, BASE_ABST_ATR_ID bigint, READ_ONLY bit, SKIP_LOGIC bit, HEADING varchar(255), yPosition integer, SKIP_LOGIC_TARGET_CONTROL bit, SOURCE_CONTROL_ID bigint, SHOW_HIDE bit, SELECTIVE_READ_ONLY bit, primary key (IDENTIFIER));
create table DYEXTN_DATABASE_PROPERTIES (IDENTIFIER bigint not null auto_increment, NAME varchar(255), primary key (IDENTIFIER));
create table DYEXTN_DATA_ELEMENT (IDENTIFIER bigint not null auto_increment, CATEGORY_ATTRIBUTE_ID bigint, SKIP_LOGIC_ATTRIBUTE_ID bigint, ATTRIBUTE_TYPE_INFO_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_DATA_GRID (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_DATEPICKER (IDENTIFIER bigint not null, SHOWCALENDAR bit, DATE_VALUE_TYPE varchar(255), primary key (IDENTIFIER));
create table DYEXTN_DATE_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE datetime, primary key (IDENTIFIER));
create table DYEXTN_DATE_TYPE_INFO (IDENTIFIER bigint not null, FORMAT varchar(255), primary key (IDENTIFIER));
create table DYEXTN_DOUBLE_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE double precision, primary key (IDENTIFIER));
create table DYEXTN_DOUBLE_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_ENTITY (IDENTIFIER bigint not null, DATA_TABLE_STATE integer, ENTITY_GROUP_ID bigint, IS_ABSTRACT bit, PARENT_ENTITY_ID bigint, INHERITANCE_STRATEGY integer, DISCRIMINATOR_COLUMN_NAME varchar(255), DISCRIMINATOR_VALUE varchar(255), primary key (IDENTIFIER));
create table DYEXTN_ENTITY_GROUP (IDENTIFIER bigint not null, LONG_NAME varchar(255), SHORT_NAME varchar(255), VERSION varchar(255), IS_SYSTEM_GENERATED bit, primary key (IDENTIFIER));
create table DYEXTN_ENTIY_COMPOSITE_KEY_REL (ENTITY_ID bigint not null, ATTRIBUTE_ID bigint not null, INSERTION_ORDER integer not null, primary key (ENTITY_ID, INSERTION_ORDER));
create table DYEXTN_FILE_EXTENSIONS (IDENTIFIER bigint not null auto_increment, FILE_EXTENSION varchar(255), ATTRIBUTE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_FILE_TYPE_INFO (IDENTIFIER bigint not null, MAX_FILE_SIZE float, primary key (IDENTIFIER));
create table DYEXTN_FILE_UPLOAD (IDENTIFIER bigint not null, NO_OF_COLUMNS integer, primary key (IDENTIFIER));
create table DYEXTN_FLOAT_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE float, primary key (IDENTIFIER));
create table DYEXTN_FLOAT_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_FORMULA (IDENTIFIER bigint not null auto_increment, EXPRESSION varchar(255), CATEGORY_ATTRIBUTE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_FORM_CTRL_NOTES (IDENTIFIER bigint not null auto_increment, NOTE varchar(255), FORM_CONTROL_ID bigint, INSERTION_ORDER integer, primary key (IDENTIFIER));
create table DYEXTN_INTEGER_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE integer, primary key (IDENTIFIER));
create table DYEXTN_INTEGER_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_LABEL (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_LIST_BOX (IDENTIFIER bigint not null, NO_OF_ROWS integer, MULTISELECT bit, USE_AUTOCOMPLETE bit, primary key (IDENTIFIER));
create table DYEXTN_LONG_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE bigint, primary key (IDENTIFIER));
create table DYEXTN_LONG_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_MULTISELECT_CHECK_BOX (IDENTIFIER bigint not null, MULTISELECT bit, primary key (IDENTIFIER));
create table DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER bigint not null, MEASUREMENT_UNITS varchar(255), DECIMAL_PLACES integer, NO_DIGITS integer, primary key (IDENTIFIER));
create table DYEXTN_OBJECT_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_PATH (IDENTIFIER bigint not null auto_increment, CATEGORY_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_PATH_ASSO_REL (IDENTIFIER bigint not null auto_increment, PATH_ID bigint, ASSOCIATION_ID bigint, PATH_SEQUENCE_NUMBER integer, SRC_INSTANCE_ID bigint, TGT_INSTANCE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER bigint not null auto_increment, DESCRIPTION varchar(255), CATEGORY_ATTRIBUTE_ID bigint, SKIP_LOGIC_CAT_ATTR_ID bigint, SKIP_LOGIC_ATTRIBUTE_ID bigint, ATTRIBUTE_TYPE_INFO_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER bigint not null, IS_IDENTIFIED bit, IS_PRIMARY_KEY bit, IS_NULLABLE bit, primary key (IDENTIFIER));
create table DYEXTN_RADIOBUTTON (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_ROLE (IDENTIFIER bigint not null auto_increment, ASSOCIATION_TYPE varchar(255), MAX_CARDINALITY integer, MIN_CARDINALITY integer, NAME varchar(255), primary key (IDENTIFIER));
create table DYEXTN_RULE (IDENTIFIER bigint not null auto_increment, NAME varchar(255), IS_IMPLICIT bit, ATTRIBUTE_ID bigint, CATEGORY_ATTR_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_RULE_PARAMETER (IDENTIFIER bigint not null auto_increment, NAME varchar(255), VALUE varchar(255), RULE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_SELECT_CONTROL (IDENTIFIER bigint not null, SEPARATOR_STRING varchar(255), primary key (IDENTIFIER));
create table DYEXTN_SEMANTIC_PROPERTY (IDENTIFIER bigint not null auto_increment, CONCEPT_CODE varchar(255), TERM varchar(255), THESAURAS_NAME varchar(255), SEQUENCE_NUMBER integer, CONCEPT_DEFINITION varchar(255), ABSTRACT_METADATA_ID bigint, ABSTRACT_VALUE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_SHORT_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE smallint, primary key (IDENTIFIER));
create table DYEXTN_SHORT_TYPE_INFO (IDENTIFIER bigint not null, primary key (IDENTIFIER));
create table DYEXTN_SKIP_LOGIC_ATTRIBUTE (IDENTIFIER bigint not null, SOURCE_SKIP_LOGIC_ID bigint, TARGET_SKIP_LOGIC_ID bigint, CAT_ATTR_ID bigint, PERM_VALUE_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_SQL_AUDIT (IDENTIFIER bigint not null auto_increment, AUDIT_DATE datetime, QUERY_EXECUTED text, USER_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_STRING_CONCEPT_VALUE (IDENTIFIER bigint not null, VALUE varchar(255), primary key (IDENTIFIER));
create table DYEXTN_STRING_TYPE_INFO (IDENTIFIER bigint not null, MAX_SIZE integer, primary key (IDENTIFIER));
create table DYEXTN_TABLE_PROPERTIES (IDENTIFIER bigint not null, ABSTRACT_ENTITY_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_TAGGED_VALUE (IDENTIFIER bigint not null auto_increment, T_KEY varchar(255), T_VALUE varchar(255), ABSTRACT_METADATA_ID bigint, primary key (IDENTIFIER));
create table DYEXTN_TEXTAREA (IDENTIFIER bigint not null, TEXTAREA_COLUMNS integer, TEXTAREA_ROWS integer, primary key (IDENTIFIER));
create table DYEXTN_TEXTFIELD (IDENTIFIER bigint not null, NO_OF_COLUMNS integer, IS_PASSWORD bit, IS_URL bit, primary key (IDENTIFIER));
create table DYEXTN_USERDEFINED_DE (IDENTIFIER bigint not null, IS_ORDERED bit, primary key (IDENTIFIER));
create table DYEXTN_USERDEF_DE_VALUE_REL (USER_DEF_DE_ID bigint not null, PERMISSIBLE_VALUE_ID bigint not null, primary key (USER_DEF_DE_ID, PERMISSIBLE_VALUE_ID));
create table DYEXTN_VIEW (IDENTIFIER bigint not null auto_increment, NAME varchar(255), primary key (IDENTIFIER));
create table PATH (PATH_ID bigint not null auto_increment, FIRST_ENTITY_ID bigint, LAST_ENTITY_ID bigint, INTERMEDIATE_PATH varchar(150), primary key (PATH_ID));
create table dyextn_id_generator (id bigint not null, next_available_id bigint, primary key (id));
alter table ABSTRACT_CATEGORIAL_CLASS add index FK6C8779AF8168C18B (PARENT_CATEGORIAL_CLASS_ID), add constraint FK6C8779AF8168C18B foreign key (PARENT_CATEGORIAL_CLASS_ID) references ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER);
alter table ABSTRACT_CATEGORIAL_CLASS add index FK6C8779AF1E10D264 (ABSTRACT_CATEGORY_ID), add constraint FK6C8779AF1E10D264 foreign key (ABSTRACT_CATEGORY_ID) references ABSTRACT_CATEGORY (ID);
alter table ABSTRACT_CATEGORY add index FK92BB047B70295EEC (PARENT_CATEGORY_ID), add constraint FK92BB047B70295EEC foreign key (PARENT_CATEGORY_ID) references ABSTRACT_CATEGORY (ID);
alter table CATEGORIAL_ATTRIBUTE add index FK31F77B5634ED55B7 (ID), add constraint FK31F77B5634ED55B7 foreign key (ID) references DYEXTN_ABSTR_CAT_ATTR (ID);
alter table CATEGORIAL_CLASS add index FK9651EF32F94A5493 (ID), add constraint FK9651EF32F94A5493 foreign key (ID) references ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER);
alter table CATEGORY add index FK31A8ACFEC88316F9 (ROOT_CLASS_ID), add constraint FK31A8ACFEC88316F9 foreign key (ROOT_CLASS_ID) references CATEGORIAL_CLASS (ID);
alter table CATEGORY add index FK31A8ACFEA2330820 (ID), add constraint FK31A8ACFEA2330820 foreign key (ID) references ABSTRACT_CATEGORY (ID);
alter table CURATED_PATH_TO_PATH add index FK9D8A323C20A0CA98 (PATH_ID), add constraint FK9D8A323C20A0CA98 foreign key (PATH_ID) references PATH (PATH_ID);
alter table CURATED_PATH_TO_PATH add index FK9D8A323C7D782761 (CURATED_PATH_ID), add constraint FK9D8A323C7D782761 foreign key (CURATED_PATH_ID) references CURATED_PATH (CURATED_PATH_ID);
alter table DE_COLL_ATTR_RECORD_VALUES add index FK847DA57775255CA5 (COLLECTION_ATTR_RECORD_ID), add constraint FK847DA57775255CA5 foreign key (COLLECTION_ATTR_RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD (IDENTIFIER);
alter table DE_FILE_ATTR_RECORD_VALUES add index FKE68334E74EB991B2 (RECORD_ID), add constraint FKE68334E74EB991B2 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD (IDENTIFIER);
alter table DE_OBJECT_ATTR_RECORD_VALUES add index FK504EADC44EB991B2 (RECORD_ID), add constraint FK504EADC44EB991B2 foreign key (RECORD_ID) references DYEXTN_ATTRIBUTE_RECORD (IDENTIFIER);
alter table DYEXTN_ABSTRACT_ENTITY add index FKA4A164E3D3027A30 (id), add constraint FKA4A164E3D3027A30 foreign key (id) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_ABSTRACT_RECORD_ENTRY add index FKA74A5FE4DDFB1974 (ABSTRACT_FORM_CONTEXT_ID), add constraint FKA74A5FE4DDFB1974 foreign key (ABSTRACT_FORM_CONTEXT_ID) references DYEXTN_ABSTRACT_FORM_CONTEXT (IDENTIFIER);
alter table DYEXTN_ABSTR_CAT_ATTR add index FK144CAB469195652D (ABSTR_CATEGORIAL_ATTRIBUTE_ID), add constraint FK144CAB469195652D foreign key (ABSTR_CATEGORIAL_ATTRIBUTE_ID) references ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER);
alter table DYEXTN_ABSTR_CAT_ATTR add index FK144CAB46A5F024A0 (CATEGORIAL_CLASS_ID), add constraint FK144CAB46A5F024A0 foreign key (CATEGORIAL_CLASS_ID) references ABSTRACT_CATEGORIAL_CLASS (IDENTIFIER);
alter table DYEXTN_ABSTR_CONTAIN_CTR add index FK9EB9020A40F198C2 (IDENTIFIER), add constraint FK9EB9020A40F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_ABSTR_CONTAIN_CTR add index FK9EB9020A69935DD6 (CONTAINER_ID), add constraint FK9EB9020A69935DD6 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER (IDENTIFIER);
alter table DYEXTN_ASSOCIATION add index FK1046842439780F7A (SOURCE_ROLE_ID), add constraint FK1046842439780F7A foreign key (SOURCE_ROLE_ID) references DYEXTN_ROLE (IDENTIFIER);
alter table DYEXTN_ASSOCIATION add index FK104684242BD842F0 (TARGET_ROLE_ID), add constraint FK104684242BD842F0 foreign key (TARGET_ROLE_ID) references DYEXTN_ROLE (IDENTIFIER);
alter table DYEXTN_ASSOCIATION add index FK1046842440738A50 (TARGET_ENTITY_ID), add constraint FK1046842440738A50 foreign key (TARGET_ENTITY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_ASSOCIATION add index FK104684246D19A21F (IDENTIFIER), add constraint FK104684246D19A21F foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_ASSO_DISPLAY_ATTR add index FKD12FD3827FD29CDD (SELECT_CONTROL_ID), add constraint FKD12FD3827FD29CDD foreign key (SELECT_CONTROL_ID) references DYEXTN_SELECT_CONTROL (IDENTIFIER);
alter table DYEXTN_ASSO_DISPLAY_ATTR add index FKD12FD38235D6E973 (DISPLAY_ATTRIBUTE_ID), add constraint FKD12FD38235D6E973 foreign key (DISPLAY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_ATTRIBUTE add index FK37F1E2FFF99EA906 (ENTIY_ID), add constraint FK37F1E2FFF99EA906 foreign key (ENTIY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_ATTRIBUTE add index FK37F1E2FF5CC8694E (IDENTIFIER), add constraint FK37F1E2FF5CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_ATTRIBUTE_RECORD add index FK9B20ED914AC41F7E (ENTITY_ID), add constraint FK9B20ED914AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_ATTRIBUTE_RECORD add index FK9B20ED914DC2CD16 (ATTRIBUTE_ID), add constraint FK9B20ED914DC2CD16 foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_ATTRIBUTE_TYPE_INFO add index FK62596D531333996E (PRIMITIVE_ATTRIBUTE_ID), add constraint FK62596D531333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_BARR_CONCEPT_VALUE add index FK89D27DF74641D513 (IDENTIFIER), add constraint FK89D27DF74641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_BASE_ABSTRACT_ATTRIBUTE add index FK14BA6610728B19BE (IDENTIFIER), add constraint FK14BA6610728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_BOOLEAN_CONCEPT_VALUE add index FK57B6C4A64641D513 (IDENTIFIER), add constraint FK57B6C4A64641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_BOOLEAN_TYPE_INFO add index FK28F1809FE5294FA3 (IDENTIFIER), add constraint FK28F1809FE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_BYTE_ARRAY_TYPE_INFO add index FK18BDA73E5294FA3 (IDENTIFIER), add constraint FK18BDA73E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_CADSRDE add index FK588A250953CC4A77 (IDENTIFIER), add constraint FK588A250953CC4A77 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT (IDENTIFIER);
alter table DYEXTN_CADSR_VALUE_DOMAIN_INFO add index FK1C9AA3641333996E (PRIMITIVE_ATTRIBUTE_ID), add constraint FK1C9AA3641333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CALCULATED_ATTRIBUTE add index FK8D70ECD8B314DD24 (TARGET_CAL_ATTR_ID), add constraint FK8D70ECD8B314DD24 foreign key (TARGET_CAL_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CALCULATED_ATTRIBUTE add index FK8D70ECD8BDAACCB6 (SOURCE_CAT_ATTR_ID), add constraint FK8D70ECD8BDAACCB6 foreign key (SOURCE_CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CALCULATED_ATTRIBUTE add index FK8D70ECD85CC8694E (IDENTIFIER), add constraint FK8D70ECD85CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CALCULATED_ATTRIBUTE add index FK8D70ECD85697A453 (CAL_CATEGORY_ATTR_ID), add constraint FK8D70ECD85697A453 foreign key (CAL_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY add index FKD33DE81B54A9F59D (ROOT_CATEGORY_ELEMENT), add constraint FKD33DE81B54A9F59D foreign key (ROOT_CATEGORY_ELEMENT) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY add index FKD33DE81B728B19BE (IDENTIFIER), add constraint FKD33DE81B728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_CATEGORY add index FKD33DE81B854AC01B (CATEGORY_ENTITY_ID), add constraint FKD33DE81B854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ASSOCIATION add index FK1B7C663DCAC769C5 (CATEGORY_ENTIY_ID), add constraint FK1B7C663DCAC769C5 foreign key (CATEGORY_ENTIY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ASSOCIATION add index FK1B7C663D5CC8694E (IDENTIFIER), add constraint FK1B7C663D5CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY_ASSOCIATION add index FK1B7C663D854AC01B (CATEGORY_ENTITY_ID), add constraint FK1B7C663D854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B7758A2CA8853 (CAL_DEPENDENT_CATEGORY_ATTR_ID), add constraint FKEF3B7758A2CA8853 foreign key (CAL_DEPENDENT_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B7758CAC769C5 (CATEGORY_ENTIY_ID), add constraint FKEF3B7758CAC769C5 foreign key (CATEGORY_ENTIY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B77587769A811 (ABSTRACT_ATTRIBUTE_ID), add constraint FKEF3B77587769A811 foreign key (ABSTRACT_ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B77585CC8694E (IDENTIFIER), add constraint FKEF3B77585CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B7758854AC01B (CATEGORY_ENTITY_ID), add constraint FKEF3B7758854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ATTRIBUTE add index FKEF3B77585697A453 (CAL_CATEGORY_ATTR_ID), add constraint FKEF3B77585697A453 foreign key (CAL_CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887FB6EB979 (CATEGORY_ASSOCIATION_ID), add constraint FK9F2DA887FB6EB979 foreign key (CATEGORY_ASSOCIATION_ID) references DYEXTN_CATEGORY_ASSOCIATION (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887D06EE657 (OWN_PARENT_CATEGORY_ENTITY_ID), add constraint FK9F2DA887D06EE657 foreign key (OWN_PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887A52559D0 (PARENT_CATEGORY_ENTITY_ID), add constraint FK9F2DA887A52559D0 foreign key (PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887743AC3F2 (IDENTIFIER), add constraint FK9F2DA887743AC3F2 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_ENTITY (id);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA8874AC41F7E (ENTITY_ID), add constraint FK9F2DA8874AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887F5A32608 (REL_ATTR_CAT_ENTITY_ID), add constraint FK9F2DA887F5A32608 foreign key (REL_ATTR_CAT_ENTITY_ID) references DYEXTN_CATEGORY (IDENTIFIER);
alter table DYEXTN_CATEGORY_ENTITY add index FK9F2DA887A8103C6F (TREE_PARENT_CATEGORY_ENTITY_ID), add constraint FK9F2DA887A8103C6F foreign key (TREE_PARENT_CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_CAT_ASSO_CTL add index FK281FAB50C45A8CFA (IDENTIFIER), add constraint FK281FAB50C45A8CFA foreign key (IDENTIFIER) references DYEXTN_ABSTR_CONTAIN_CTR (IDENTIFIER);
alter table DYEXTN_CHECK_BOX add index FK4EFF925740F198C2 (IDENTIFIER), add constraint FK4EFF925740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_COLUMN_PROPERTIES add index FK8FCE2B3F67F8B59 (CATEGORY_ATTRIBUTE_ID), add constraint FK8FCE2B3F67F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_COLUMN_PROPERTIES add index FK8FCE2B3F4953F037 (CNSTR_KEY_PROP_ID), add constraint FK8FCE2B3F4953F037 foreign key (CNSTR_KEY_PROP_ID) references DYEXTN_CONSTRAINTKEY_PROP (IDENTIFIER);
alter table DYEXTN_COLUMN_PROPERTIES add index FK8FCE2B3F3AB6A1D3 (IDENTIFIER), add constraint FK8FCE2B3F3AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES (IDENTIFIER);
alter table DYEXTN_COLUMN_PROPERTIES add index FK8FCE2B3F1333996E (PRIMITIVE_ATTRIBUTE_ID), add constraint FK8FCE2B3F1333996E foreign key (PRIMITIVE_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_COMBOBOX add index FKABBC649ABF67AB26 (IDENTIFIER), add constraint FKABBC649ABF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL (IDENTIFIER);
alter table DYEXTN_CONSTRAINTKEY_PROP add index FK80C9511D6B558E0E (SRC_CONSTRAINT_KEY_ID), add constraint FK80C9511D6B558E0E foreign key (SRC_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES (IDENTIFIER);
alter table DYEXTN_CONSTRAINTKEY_PROP add index FK80C9511D2C4ACB4B (TGT_CONSTRAINT_KEY_ID), add constraint FK80C9511D2C4ACB4B foreign key (TGT_CONSTRAINT_KEY_ID) references DYEXTN_CONSTRAINT_PROPERTIES (IDENTIFIER);
alter table DYEXTN_CONSTRAINTKEY_PROP add index FK80C9511DF3077C33 (PRIMARY_ATTRIBUTE_ID), add constraint FK80C9511DF3077C33 foreign key (PRIMARY_ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CONSTRAINT_PROPERTIES add index FK82886CD8FB6EB979 (CATEGORY_ASSOCIATION_ID), add constraint FK82886CD8FB6EB979 foreign key (CATEGORY_ASSOCIATION_ID) references DYEXTN_CATEGORY_ASSOCIATION (IDENTIFIER);
alter table DYEXTN_CONSTRAINT_PROPERTIES add index FK82886CD87EE87FF6 (ASSOCIATION_ID), add constraint FK82886CD87EE87FF6 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION (IDENTIFIER);
alter table DYEXTN_CONSTRAINT_PROPERTIES add index FK82886CD83AB6A1D3 (IDENTIFIER), add constraint FK82886CD83AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES (IDENTIFIER);
alter table DYEXTN_CONSTRAINT_PROPERTIES add index FK82886CD81DCC9E63 (ABSTRACT_ENTITY_ID), add constraint FK82886CD81DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY (id);
alter table DYEXTN_CONTAINER add index FK1EAB84E488C075EF (ENTITY_GROUP_ID), add constraint FK1EAB84E488C075EF foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP (IDENTIFIER);
alter table DYEXTN_CONTAINER add index FK1EAB84E440FCA34B (PARENT_CONTAINER_ID), add constraint FK1EAB84E440FCA34B foreign key (PARENT_CONTAINER_ID) references DYEXTN_CONTAINER (IDENTIFIER);
alter table DYEXTN_CONTAINER add index FK1EAB84E4BF901C84 (BASE_CONTAINER_ID), add constraint FK1EAB84E4BF901C84 foreign key (BASE_CONTAINER_ID) references DYEXTN_CONTAINER (IDENTIFIER);
alter table DYEXTN_CONTAINER add index FK1EAB84E41DCC9E63 (ABSTRACT_ENTITY_ID), add constraint FK1EAB84E41DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY (id);
alter table DYEXTN_CONTAINER add index FK1EAB84E4178865E (VIEW_ID), add constraint FK1EAB84E4178865E foreign key (VIEW_ID) references DYEXTN_VIEW (IDENTIFIER);
alter table DYEXTN_CONTAINMENT_CONTROL add index FK3F9D4AD3C45A8CFA (IDENTIFIER), add constraint FK3F9D4AD3C45A8CFA foreign key (IDENTIFIER) references DYEXTN_ABSTR_CONTAIN_CTR (IDENTIFIER);
alter table DYEXTN_CONTROL add index FK70FB5E807792A78F (BASE_ABST_ATR_ID), add constraint FK70FB5E807792A78F foreign key (BASE_ABST_ATR_ID) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_CONTROL add index FK70FB5E80FEA07DFA (SOURCE_CONTROL_ID), add constraint FK70FB5E80FEA07DFA foreign key (SOURCE_CONTROL_ID) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_CONTROL add index FK70FB5E8069935DD6 (CONTAINER_ID), add constraint FK70FB5E8069935DD6 foreign key (CONTAINER_ID) references DYEXTN_CONTAINER (IDENTIFIER);
alter table DYEXTN_DATA_ELEMENT add index FKB1153E4791A6280 (SKIP_LOGIC_ATTRIBUTE_ID), add constraint FKB1153E4791A6280 foreign key (SKIP_LOGIC_ATTRIBUTE_ID) references DYEXTN_SKIP_LOGIC_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_DATA_ELEMENT add index FKB1153E4AA208204 (ATTRIBUTE_TYPE_INFO_ID), add constraint FKB1153E4AA208204 foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_DATA_ELEMENT add index FKB1153E467F8B59 (CATEGORY_ATTRIBUTE_ID), add constraint FKB1153E467F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_DATA_GRID add index FK233EB73E40F198C2 (IDENTIFIER), add constraint FK233EB73E40F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_DATEPICKER add index FKFEADD19940F198C2 (IDENTIFIER), add constraint FKFEADD19940F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_DATE_CONCEPT_VALUE add index FK45F598A64641D513 (IDENTIFIER), add constraint FK45F598A64641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_DATE_TYPE_INFO add index FKFBA549FE5294FA3 (IDENTIFIER), add constraint FKFBA549FE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_DOUBLE_CONCEPT_VALUE add index FKB94E64494641D513 (IDENTIFIER), add constraint FKB94E64494641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_DOUBLE_TYPE_INFO add index FKC83869C2BA4AE008 (IDENTIFIER), add constraint FKC83869C2BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_ENTITY add index FK8B24364088C075EF (ENTITY_GROUP_ID), add constraint FK8B24364088C075EF foreign key (ENTITY_GROUP_ID) references DYEXTN_ENTITY_GROUP (IDENTIFIER);
alter table DYEXTN_ENTITY add index FK8B2436402264D629 (PARENT_ENTITY_ID), add constraint FK8B2436402264D629 foreign key (PARENT_ENTITY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_ENTITY add index FK8B243640743AC3F2 (IDENTIFIER), add constraint FK8B243640743AC3F2 foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_ENTITY (id);
alter table DYEXTN_ENTITY_GROUP add index FK105DE7A0728B19BE (IDENTIFIER), add constraint FK105DE7A0728B19BE foreign key (IDENTIFIER) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add index FKB3AA6FE04AC41F7E (ENTITY_ID), add constraint FKB3AA6FE04AC41F7E foreign key (ENTITY_ID) references DYEXTN_ENTITY (IDENTIFIER);
alter table DYEXTN_ENTIY_COMPOSITE_KEY_REL add index FKB3AA6FE04DC2CD16 (ATTRIBUTE_ID), add constraint FKB3AA6FE04DC2CD16 foreign key (ATTRIBUTE_ID) references DYEXTN_PRIMITIVE_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_FILE_EXTENSIONS add index FKD49834FA56AF0834 (ATTRIBUTE_ID), add constraint FKD49834FA56AF0834 foreign key (ATTRIBUTE_ID) references DYEXTN_FILE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_FILE_TYPE_INFO add index FKA00F0EDE5294FA3 (IDENTIFIER), add constraint FKA00F0EDE5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_FILE_UPLOAD add index FK2FAD41E740F198C2 (IDENTIFIER), add constraint FK2FAD41E740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_FLOAT_CONCEPT_VALUE add index FK6785309A4641D513 (IDENTIFIER), add constraint FK6785309A4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_FLOAT_TYPE_INFO add index FK7E1C0693BA4AE008 (IDENTIFIER), add constraint FK7E1C0693BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_FORMULA add index FKFE34A8967F8B59 (CATEGORY_ATTRIBUTE_ID), add constraint FKFE34A8967F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_FORM_CTRL_NOTES add index FK7A0DA06B41D885B1 (FORM_CONTROL_ID), add constraint FK7A0DA06B41D885B1 foreign key (FORM_CONTROL_ID) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_INTEGER_CONCEPT_VALUE add index FKFBA33B3C4641D513 (IDENTIFIER), add constraint FKFBA33B3C4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_INTEGER_TYPE_INFO add index FK5F9CB235BA4AE008 (IDENTIFIER), add constraint FK5F9CB235BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_LABEL add index FK787668D740F198C2 (IDENTIFIER), add constraint FK787668D740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_LIST_BOX add index FK208395A7BF67AB26 (IDENTIFIER), add constraint FK208395A7BF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL (IDENTIFIER);
alter table DYEXTN_LONG_CONCEPT_VALUE add index FK3E1A6EF44641D513 (IDENTIFIER), add constraint FK3E1A6EF44641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_LONG_TYPE_INFO add index FK257281EDBA4AE008 (IDENTIFIER), add constraint FK257281EDBA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_MULTISELECT_CHECK_BOX add index FK4312896DBF67AB26 (IDENTIFIER), add constraint FK4312896DBF67AB26 foreign key (IDENTIFIER) references DYEXTN_SELECT_CONTROL (IDENTIFIER);
alter table DYEXTN_NUMERIC_TYPE_INFO add index FK4DEC9544E5294FA3 (IDENTIFIER), add constraint FK4DEC9544E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_OBJECT_TYPE_INFO add index FK74819FB0E5294FA3 (IDENTIFIER), add constraint FK74819FB0E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_PATH add index FKC26ADC2854AC01B (CATEGORY_ENTITY_ID), add constraint FKC26ADC2854AC01B foreign key (CATEGORY_ENTITY_ID) references DYEXTN_CATEGORY_ENTITY (IDENTIFIER);
alter table DYEXTN_PATH_ASSO_REL add index FK1E1260A580C8F93E (PATH_ID), add constraint FK1E1260A580C8F93E foreign key (PATH_ID) references DYEXTN_PATH (IDENTIFIER);
alter table DYEXTN_PATH_ASSO_REL add index FK1E1260A57EE87FF6 (ASSOCIATION_ID), add constraint FK1E1260A57EE87FF6 foreign key (ASSOCIATION_ID) references DYEXTN_ASSOCIATION (IDENTIFIER);
alter table DYEXTN_PERMISSIBLE_VALUE add index FK136264E0668894B9 (SKIP_LOGIC_CAT_ATTR_ID), add constraint FK136264E0668894B9 foreign key (SKIP_LOGIC_CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_PERMISSIBLE_VALUE add index FK136264E0791A6280 (SKIP_LOGIC_ATTRIBUTE_ID), add constraint FK136264E0791A6280 foreign key (SKIP_LOGIC_ATTRIBUTE_ID) references DYEXTN_SKIP_LOGIC_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_PERMISSIBLE_VALUE add index FK136264E0AA208204 (ATTRIBUTE_TYPE_INFO_ID), add constraint FK136264E0AA208204 foreign key (ATTRIBUTE_TYPE_INFO_ID) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_PERMISSIBLE_VALUE add index FK136264E067F8B59 (CATEGORY_ATTRIBUTE_ID), add constraint FK136264E067F8B59 foreign key (CATEGORY_ATTRIBUTE_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_PRIMITIVE_ATTRIBUTE add index FKA9F765C76D19A21F (IDENTIFIER), add constraint FKA9F765C76D19A21F foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_RADIOBUTTON add index FK16F5BA9040F198C2 (IDENTIFIER), add constraint FK16F5BA9040F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_RULE add index FKC27E099F8DDEC02 (CATEGORY_ATTR_ID), add constraint FKC27E099F8DDEC02 foreign key (CATEGORY_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_RULE add index FKC27E09990F96714 (ATTRIBUTE_ID), add constraint FKC27E09990F96714 foreign key (ATTRIBUTE_ID) references DYEXTN_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_RULE_PARAMETER add index FK2256736395D4A5AE (RULE_ID), add constraint FK2256736395D4A5AE foreign key (RULE_ID) references DYEXTN_RULE (IDENTIFIER);
alter table DYEXTN_SELECT_CONTROL add index FKDFEBB65740F198C2 (IDENTIFIER), add constraint FKDFEBB65740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_SEMANTIC_PROPERTY add index FKD2A0B5B15EB60E90 (ABSTRACT_VALUE_ID), add constraint FKD2A0B5B15EB60E90 foreign key (ABSTRACT_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_SEMANTIC_PROPERTY add index FKD2A0B5B19AEB0CA3 (ABSTRACT_METADATA_ID), add constraint FKD2A0B5B19AEB0CA3 foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_SHORT_CONCEPT_VALUE add index FKC1945ABA4641D513 (IDENTIFIER), add constraint FKC1945ABA4641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_SHORT_TYPE_INFO add index FK99540B3BA4AE008 (IDENTIFIER), add constraint FK99540B3BA4AE008 foreign key (IDENTIFIER) references DYEXTN_NUMERIC_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add index FK722F03989F433752 (SOURCE_SKIP_LOGIC_ID), add constraint FK722F03989F433752 foreign key (SOURCE_SKIP_LOGIC_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add index FK722F039889907A48 (TARGET_SKIP_LOGIC_ID), add constraint FK722F039889907A48 foreign key (TARGET_SKIP_LOGIC_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add index FK722F03985CC8694E (IDENTIFIER), add constraint FK722F03985CC8694E foreign key (IDENTIFIER) references DYEXTN_BASE_ABSTRACT_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add index FK722F0398DB856DA (CAT_ATTR_ID), add constraint FK722F0398DB856DA foreign key (CAT_ATTR_ID) references DYEXTN_CATEGORY_ATTRIBUTE (IDENTIFIER);
alter table DYEXTN_SKIP_LOGIC_ATTRIBUTE add index FK722F0398B96D382 (PERM_VALUE_ID), add constraint FK722F0398B96D382 foreign key (PERM_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_STRING_CONCEPT_VALUE add index FKADE7D8894641D513 (IDENTIFIER), add constraint FKADE7D8894641D513 foreign key (IDENTIFIER) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_STRING_TYPE_INFO add index FKDA35FE02E5294FA3 (IDENTIFIER), add constraint FKDA35FE02E5294FA3 foreign key (IDENTIFIER) references DYEXTN_ATTRIBUTE_TYPE_INFO (IDENTIFIER);
alter table DYEXTN_TABLE_PROPERTIES add index FKE608E0813AB6A1D3 (IDENTIFIER), add constraint FKE608E0813AB6A1D3 foreign key (IDENTIFIER) references DYEXTN_DATABASE_PROPERTIES (IDENTIFIER);
alter table DYEXTN_TABLE_PROPERTIES add index FKE608E0811DCC9E63 (ABSTRACT_ENTITY_ID), add constraint FKE608E0811DCC9E63 foreign key (ABSTRACT_ENTITY_ID) references DYEXTN_ABSTRACT_ENTITY (id);
alter table DYEXTN_TAGGED_VALUE add index FKF79D055B9AEB0CA3 (ABSTRACT_METADATA_ID), add constraint FKF79D055B9AEB0CA3 foreign key (ABSTRACT_METADATA_ID) references DYEXTN_ABSTRACT_METADATA (IDENTIFIER);
alter table DYEXTN_TEXTAREA add index FK946EE25740F198C2 (IDENTIFIER), add constraint FK946EE25740F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_TEXTFIELD add index FKF9AFC85040F198C2 (IDENTIFIER), add constraint FKF9AFC85040F198C2 foreign key (IDENTIFIER) references DYEXTN_CONTROL (IDENTIFIER);
alter table DYEXTN_USERDEFINED_DE add index FK630761FF53CC4A77 (IDENTIFIER), add constraint FK630761FF53CC4A77 foreign key (IDENTIFIER) references DYEXTN_DATA_ELEMENT (IDENTIFIER);
alter table DYEXTN_USERDEF_DE_VALUE_REL add index FK3EE58DCF49BDD67 (PERMISSIBLE_VALUE_ID), add constraint FK3EE58DCF49BDD67 foreign key (PERMISSIBLE_VALUE_ID) references DYEXTN_PERMISSIBLE_VALUE (IDENTIFIER);
alter table DYEXTN_USERDEF_DE_VALUE_REL add index FK3EE58DCF5521B106 (USER_DEF_DE_ID), add constraint FK3EE58DCF5521B106 foreign key (USER_DEF_DE_ID) references DYEXTN_USERDEFINED_DE (IDENTIFIER);

drop table if exists INTER_MODEL_ASSOCIATION;
drop table if exists INTRA_MODEL_ASSOCIATION;
drop table if exists ASSOCIATION;

/* Possible values for ASSOCIATION_TYPE are 1 and 2
ASSOCIATION_TYPE = 1 represents INTER_MODEL_ASSOCIATION.
ASSOCIATION_TYPE = 2 represents INTRA_MODEL_ASSOCIATION.
*/
create table ASSOCIATION(
    ASSOCIATION_ID    bigint    not null,
    ASSOCIATION_TYPE  INT(8)    not null ,
    primary key (ASSOCIATION_ID)
);

create table INTER_MODEL_ASSOCIATION(
    ASSOCIATION_ID      bigint  not null references ASSOCIATION(ASSOCIATION_ID),
    LEFT_ENTITY_ID      bigint  not null,
    LEFT_ATTRIBUTE_ID   bigint  not null,
    RIGHT_ENTITY_ID     bigint  not null,
    RIGHT_ATTRIBUTE_ID  bigint  not null,
    primary key (ASSOCIATION_ID)
);
create table INTRA_MODEL_ASSOCIATION(
    ASSOCIATION_ID    bigint    not null references ASSOCIATION(ASSOCIATION_ID),
    DE_ASSOCIATION_ID bigint    not null,
    primary key (ASSOCIATION_ID)
);


drop table if exists ID_TABLE;

create table ID_TABLE(
    NEXT_ASSOCIATION_ID    bigint    not null,
    primary key (NEXT_ASSOCIATION_ID)
);

insert into ID_TABLE(NEXT_ASSOCIATION_ID) values(1);

commit;