//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.07.14 at 08:49:23 PM IST
//


package edu.common.dynamicextensions.util.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sourceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="sourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primary-definition" type="{}primaryDefinitionType"/>
 *         &lt;element name="qualifier-definition">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="qualifier" type="{}qualifierType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sourceType", propOrder = {
    "primaryDefinition",
    "qualifierDefinition"
})
public class SourceType {

    @XmlElement(name = "primary-definition")
    protected PrimaryDefinitionType primaryDefinition;
    @XmlElement(name = "qualifier-definition")
    protected QualifierDefinition qualifierDefinition;

    /**
     * Gets the value of the primaryDefinition property.
     *
     * @return
     *     possible object is
     *     {@link PrimaryDefinitionType }
     *
     */
    public PrimaryDefinitionType getPrimaryDefinition() {
        return primaryDefinition;
    }

    /**
     * Sets the value of the primaryDefinition property.
     *
     * @param value
     *     allowed object is
     *     {@link PrimaryDefinitionType }
     *
     */
    public void setPrimaryDefinition(PrimaryDefinitionType value) {
        this.primaryDefinition = value;
    }

    /**
     * Gets the value of the qualifierDefinition property.
     *
     * @return
     *     possible object is
     *     {@link QualifierDefinition }
     *
     */
    public QualifierDefinition getQualifierDefinition() {
        return qualifierDefinition;
    }

    /**
     * Sets the value of the qualifierDefinition property.
     *
     * @param value
     *     allowed object is
     *     {@link QualifierDefinition }
     *
     */
    public void setQualifierDefinition(QualifierDefinition value) {
        this.qualifierDefinition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="qualifier" type="{}qualifierType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qualifier"
    })
    public static class QualifierDefinition {

        protected List<QualifierType> qualifier;

        /**
         * Gets the value of the qualifier property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qualifier property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQualifier().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QualifierType }
         *
         *
         */
        public List<QualifierType> getQualifier() {
            if (qualifier == null) {
                qualifier = new ArrayList<QualifierType>();
            }
            return this.qualifier;
        }

    }
}
