//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2010.09.08 at 03:18:04 PM GMT+05:30
//

package edu.common.dynamicextensions.util.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for validator-rules element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="validator-rules">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="validation-rule" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="error-key">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="param-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;attribute name="display-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="rule-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                   &lt;attribute name="rule-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"validationRule"})
@XmlRootElement(name = "validator-rules")
public class ValidatorRules
{

	@XmlElement(name = "validation-rule")
	protected List<ValidationRule> validationRule;

	/**
	 * Gets the value of the validationRule property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the validationRule property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getValidationRule().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ValidationRule }
	 *
	 *
	 */
	public List<ValidationRule> getValidationRule()
	{
		if (validationRule == null)
		{
			validationRule = new ArrayList<ValidationRule>();
		}
		return validationRule;
	}

	/**
	 * <p>Java class for anonymous complex type.
	 *
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 *
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="error-key">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="param" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="param-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="display-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="rule-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="rule-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 *
	 *
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {"errorKey", "param"})
	public static class ValidationRule
	{

		@XmlElement(name = "error-key")
		protected ErrorKey errorKey;
		protected List<Param> param;
		@XmlAttribute(name = "display-label", required = true)
		protected String displayLabel;
		@XmlAttribute(name = "rule-class", required = true)
		protected String ruleClass;
		@XmlAttribute(name = "rule-name", required = true)
		protected String ruleName;

		/**
		 * Gets the value of the errorKey property.
		 *
		 * @return
		 *     possible object is
		 *     {@link ErrorKey }
		 *
		 */
		public ErrorKey getErrorKey()
		{
			return errorKey;
		}

		/**
		 * Sets the value of the errorKey property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link ErrorKey }
		 *
		 */
		public void setErrorKey(ErrorKey value)
		{
			errorKey = value;
		}

		/**
		 * Gets the value of the param property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the param property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getParam().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Param }
		 *
		 *
		 */
		public List<Param> getParam()
		{
			if (param == null)
			{
				param = new ArrayList<Param>();
			}
			return param;
		}

		/**
		 * Gets the value of the displayLabel property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getDisplayLabel()
		{
			return displayLabel;
		}

		/**
		 * Sets the value of the displayLabel property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setDisplayLabel(String value)
		{
			displayLabel = value;
		}

		/**
		 * Gets the value of the ruleClass property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getRuleClass()
		{
			return ruleClass;
		}

		/**
		 * Sets the value of the ruleClass property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setRuleClass(String value)
		{
			ruleClass = value;
		}

		/**
		 * Gets the value of the ruleName property.
		 *
		 * @return
		 *     possible object is
		 *     {@link String }
		 *
		 */
		public String getRuleName()
		{
			return ruleName;
		}

		/**
		 * Sets the value of the ruleName property.
		 *
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *
		 */
		public void setRuleName(String value)
		{
			ruleName = value;
		}

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class ErrorKey
		{

			@XmlAttribute(required = true)
			protected String name;

			/**
			 * Gets the value of the name property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getName()
			{
				return name;
			}

			/**
			 * Sets the value of the name property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setName(String value)
			{
				name = value;
			}

		}

		/**
		 * <p>Java class for anonymous complex type.
		 *
		 * <p>The following schema fragment specifies the expected content contained within this class.
		 *
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="param-label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="param-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 *
		 *
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Param
		{

			@XmlAttribute(name = "param-label", required = true)
			protected String paramLabel;
			@XmlAttribute(name = "param-name", required = true)
			protected String paramName;

			/**
			 * Gets the value of the paramLabel property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getParamLabel()
			{
				return paramLabel;
			}

			/**
			 * Sets the value of the paramLabel property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setParamLabel(String value)
			{
				paramLabel = value;
			}

			/**
			 * Gets the value of the paramName property.
			 *
			 * @return
			 *     possible object is
			 *     {@link String }
			 *
			 */
			public String getParamName()
			{
				return paramName;
			}

			/**
			 * Sets the value of the paramName property.
			 *
			 * @param value
			 *     allowed object is
			 *     {@link String }
			 *
			 */
			public void setParamName(String value)
			{
				paramName = value;
			}

		}

	}

}
