//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.31 at 12:45:32 AM IST 
//


package edu.common.dynamicextensions.importer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for association complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="association">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceEntityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="targetEntityName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "association", propOrder = {
    "sourceEntityName",
    "targetEntityName"
})
public class Association {

    @XmlElement(required = true)
    protected String sourceEntityName;
    @XmlElement(required = true)
    protected String targetEntityName;

    /**
     * Gets the value of the sourceEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceEntityName() {
        return sourceEntityName;
    }

    /**
     * Sets the value of the sourceEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceEntityName(String value) {
        this.sourceEntityName = value;
    }

    /**
     * Gets the value of the targetEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntityName() {
        return targetEntityName;
    }

    /**
     * Sets the value of the targetEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntityName(String value) {
        this.targetEntityName = value;
    }

}
