//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.31 at 12:45:32 AM IST 
//


package edu.common.dynamicextensions.importer.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.common.dynamicextensions.importer.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StaticMetaData_QNAME = new QName("", "staticMetaData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.common.dynamicextensions.importer.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link StaticMetaData }
     * 
     */
    public StaticMetaData createStaticMetaData() {
        return new StaticMetaData();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StaticMetaData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "staticMetaData")
    public JAXBElement<StaticMetaData> createStaticMetaData(StaticMetaData value) {
        return new JAXBElement<StaticMetaData>(_StaticMetaData_QNAME, StaticMetaData.class, null, value);
    }

}
