//package edu.common.dynamicextensions.napi;
//
//import static edu.common.dynamicextensions.napi.FormDataManagerTestUtility.*;
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.assertNotNull;
//import static org.powermock.api.easymock.PowerMock.createMock;
//import static org.powermock.api.easymock.PowerMock.expectNew;
//import static org.powermock.api.easymock.PowerMock.replayAll;
//import static org.powermock.api.easymock.PowerMock.verifyAll;
//
//import java.io.IOException;
//import java.sql.ResultSet;
//import java.util.Arrays;
//import java.util.Calendar;
//import java.util.List;
//
//import org.junit.Before;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.powermock.core.classloader.annotations.PrepareForTest;
//import org.powermock.modules.junit4.PowerMockRunner;
//
//import edu.common.dynamicextensions.domain.nui.DatePicker;
//import edu.common.dynamicextensions.domain.nui.Page;
//import edu.common.dynamicextensions.domain.nui.StringTextField;
//import edu.common.dynamicextensions.domain.nui.SurveyContainer;
//import edu.common.dynamicextensions.napi.impl.FormDataManagerImpl;
//import edu.common.dynamicextensions.ndao.JdbcDao;
//
//@RunWith(PowerMockRunner.class)
//@PrepareForTest({FormDataManagerImpl.class, JdbcDao.class, ResultSet.class})
//public class FormDataManagerSurevyFormTest {
//
//	@Before
//	public void setUp() throws Exception {
//
//		//
//		// Setup test data
//		//
//		setUpForm();
//		setUpExpectedSqls();
//		setUpTestFormData();
//		setUpTableData();
//
//		//
//		// Mock JDBC DAO
//		//
//		mockJdbcDao = createMock(JdbcDao.class);
//		expectNew(JdbcDao.class).andReturn(mockJdbcDao);
//
//
//		//
//		// Unit under test
//		//
//		formDataMgr = new FormDataManagerImpl();
//	}
//
//	/**
//	 * TC getting form data
//	 * 
//	 * Expected Result : SUCCESS 
//	 * @throws Exception
//	 */
//	@Test
//	public void testGetFormData() throws Exception {
//		mockQueryResultSet(userTableQuery, userTabColumnNames, userTabRows);
//		mockJdbcDao.close();
//
//		replayAll();
//
//		FormData actualFormData = formDataMgr.getFormData(userProfile, 2L);
//
//		assertNotNull(actualFormData);
//		assertFormDataEquals(formData, actualFormData);
//
//	}
//
//	/**
//	 * TC for saving form data 
//	 * 
//	 * Expected Result : SUCCESS 
//	 * @throws Exception
//	 */
//	@Test
//	public void testSaveData() throws Exception {
//		mockIdGeneration("USER_PROFILES", 9933L);
//		mockUpdate(userTableInsertSql, 1);
//		mockJdbcDao.close();
//		nullifyId(formData);
//
//		replayAll();
//
//		Long expectedRecordId = 9933L;
//		Long actualRecordId = formDataMgr.saveOrUpdateFormData(null, formData);
//
//		verifyAll();
//		assertEquals(actualRecordId, expectedRecordId);
//
//	}
//
//	/**
//	 * TC for updating form data . 
//	 * Expected Result : SUCCESS 
//	 * @throws IOException 
//	 * @throws Exception
//	 */
//	@Test
//	public void testUpdateFormData() {
//		mockUpdate(userTableUpdateSql, 1);
//		mockJdbcDao.close();
//		replayAll();
//
//		Long expectedRecordId = formData.getRecordId();
//
//		Long actualRecordId = formDataMgr.saveOrUpdateFormData(null, formData);
//
//		verifyAll();
//		assertEquals(actualRecordId, expectedRecordId);
//
//	}
//
//	private void setUpForm() {
//		//
//		// 1. Setup a form as below
//		//Page: Name Details
//		//    first name: [ txt field ]
//		//    last  name: [ txt field ]
//		//Page: Personal Details
//		//    birth date: [ date picker]
//
//		userProfile = new SurveyContainer();
//		userProfile.setName("userProfile");
//		userProfile.setCaption("User Profile");
//		userProfile.setDbTableName("USER_PROFILES");
//
//		Page nameDetails = new Page("nameDetails", "Name Details");
//		userProfile.addPage(nameDetails);
//		StringTextField firstName = new StringTextField();
//		firstName.setName("firstName");
//		nameDetails.addControl(firstName);
//
//		StringTextField lastName = new StringTextField();
//		lastName.setName("lastName");
//		nameDetails.addControl(lastName);
//
//		Page personalDetails = new Page("personalDetails", "Personal Details");
//		userProfile.addPage(personalDetails);
//		DatePicker dateOfBirth = new DatePicker();
//		dateOfBirth.setName("dateOfBirth");
//		personalDetails.addControl(dateOfBirth);
//
//	}
//
//
//	private void setUpExpectedSqls() {
//		//
//		// Given below are list of SQLs expected to be generated by FormDataManagerImpl for
//		// Get form data, Insert form data, Update form data 
//		//
//		userTableQuery = "SELECT DE_A_1, DE_A_2, DE_A_3, IDENTIFIER FROM USER_PROFILES WHERE IDENTIFIER = ?";
//
//		userTableInsertSql = "INSERT INTO USER_PROFILES(DE_A_1, DE_A_2, DE_A_3, IDENTIFIER) VALUES(?, ?, ?, ?)";
//
//		userTableUpdateSql = "UPDATE USER_PROFILES SET DE_A_1 = ?, DE_A_2 = ?, DE_A_3 = ? WHERE IDENTIFIER = ?";
//	}
//
//	private void setUpTestFormData() {
//		formData = new FormData(userProfile);
//		formData.setRecordId(2L);
//		formData.addFieldValue(new ControlValue(userProfile.getControl("firstName"), "Sachin"));
//		formData.addFieldValue(new ControlValue(userProfile.getControl("lastName"), "Tendulkar"));
//		formData.addFieldValue(new ControlValue(userProfile.getControl("dateOfBirth"), "04-24-1973"));
//
//	}
//
//	private void setUpTableData() {
//		Calendar calendar = Calendar.getInstance();
//		calendar.set(1973, Calendar.APRIL, 24);
//
//		userTabColumnNames = Arrays.asList("IDENTIFIER", "DE_A_1", "DE_A_2", "DE_A_3");
//		userTabRows = new List[]{Arrays.asList(2L, "Sachin", "Tendulkar", calendar.getTime())};
//	}
//
//	//
//	// All uninteresting declarations go here
//	//
//
//	protected FormData formData;
//	
//	protected FormDataManager formDataMgr;
//
//	private SurveyContainer userProfile;
//
//	// SELECT SQLs
//	private String userTableQuery;
//
//	// Insert SQLs
//	private String userTableInsertSql;
//
//	// Update SQLs
//	private String userTableUpdateSql;
//
//	private List<String> userTabColumnNames;
//
//	private List[] userTabRows;
//}